/**
 * Stripe Checkout + License Server
 *
 * Runs alongside the relay node on the VPS. Handles:
 * 1. Creating Stripe checkout sessions (user clicks "Upgrade" in app)
 * 2. Receiving Stripe webhooks (payment confirmed)
 * 3. Generating signed license keys
 * 4. Serving license keys to authenticated users
 *
 * Environment variables:
 *   STRIPE_SECRET_KEY     — Stripe secret key (sk_test_... or sk_live_...)
 *   STRIPE_WEBHOOK_SECRET — Stripe webhook signing secret (whsec_...)
 *   STRIPE_PRICE_ID       — Price ID for OpenDescent Pro (price_...)
 *   LICENSE_PRIVATE_KEY   — Base64 Ed25519 private key for signing licenses
 *   LICENSE_PUBLIC_KEY    — Base64 Ed25519 public key (for reference)
 *
 * Usage:
 *   LICENSE_PRIVATE_KEY=... STRIPE_SECRET_KEY=sk_test_... node dist/licensing/stripe-server.js
 */

import * as http from 'http';
import * as https from 'https';
import * as crypto from 'crypto';
import { createLicense, generateLicenseKeypair } from './license.js';

// ─── Config ─────────────────────────────────────────────────────────────────

const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY || '';
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET || '';
const STRIPE_PRICE_ID = process.env.STRIPE_PRICE_ID || 'price_1TD93I13ZaqW84U7IIWJ4s1S';
const FOUNDER_PRICE_ID = process.env.FOUNDER_PRICE_ID || 'price_1THUMC238rNCK1Lkm03SMf7A';
const LICENSE_PRIVATE_KEY = process.env.LICENSE_PRIVATE_KEY || '';
const PORT = parseInt(process.env.LICENSE_PORT || '9000', 10);

// License duration: 35 days (5 day grace period beyond 30-day billing cycle)
const LICENSE_DURATION_MS = 35 * 24 * 60 * 60 * 1000;
// Founder license: expires 2030
const FOUNDER_DURATION_MS = (new Date('2030-12-31').getTime() - Date.now());
const MAX_FOUNDERS = 101;
let founderCount = 0;

// In-memory store of issued licenses (peerId -> licenseKey).
// LEGACY: written by the old peerId-in-Stripe-metadata flow. Kept readable
// so existing customers from before the redemption-code migration still work.
// New purchases never write here — they go through pendingCodes + subscriptions.
const issuedLicenses = new Map<string, string>();
const licensesFile = process.env.LICENSES_FILE || './licenses.json';

// Redemption codes generated at checkout completion. User redeems via
// POST /redeem to receive a signed license. peerId never reaches Stripe.
interface PendingCode {
  tier: 'pro';
  founder: boolean;
  /** Stripe subscription id (subscriptions only — undefined for one-shot Founder purchase) */
  subscriptionId?: string;
  /** Stripe checkout session id, used by /success to display the code */
  sessionId?: string;
  /** Whether this code was generated by a renewal (true) or first checkout (false) */
  isRenewal: boolean;
  paidAt: number;
  expiresAt: number;
}
const pendingCodes = new Map<string, PendingCode>();
const codesFile = process.env.CODES_FILE || './redemption-codes.json';

// Per-subscription record. Created at first /redeem. Tracks whether the user
// chose anonymous mode (no peerId stored) or standard mode (peerId stored
// for seamless renewals). Either way, Stripe never sees peerId.
interface SubRecord {
  /** Anonymous mode: server forgot the peerId after activation */
  anonymous: boolean;
  /** Standard mode only — populated at first redeem */
  peerId?: string;
  /** Standard mode: latest signed license, refreshed on each invoice.paid */
  latestLicense?: string;
  /** Anonymous mode: latest renewal code, replaced on each invoice.paid */
  latestRenewalCode?: string;
  /** Lifetime founder subs don't renew, but tracked here for completeness */
  founder: boolean;
  createdAt: number;
}
const subscriptions = new Map<string, SubRecord>();
const subscriptionsFile = process.env.SUBSCRIPTIONS_FILE || './subscriptions.json';

const CODE_EXPIRY_MS = 90 * 24 * 60 * 60 * 1000; // 90 days for unredeemed codes

/**
 * Generate a 16-hex-char redemption code formatted as XXXX-XXXX-XXXX-XXXX.
 * 64 bits of entropy — infeasible to brute-force given rate limiting.
 */
function generateCode(): string {
  const bytes = crypto.randomBytes(8).toString('hex').toUpperCase();
  return `${bytes.slice(0, 4)}-${bytes.slice(4, 8)}-${bytes.slice(8, 12)}-${bytes.slice(12, 16)}`;
}

function normalizeCode(input: string): string {
  return input.replace(/[\s-]/g, '').toUpperCase();
}

function findCodeByNormalized(normalized: string): string | null {
  for (const code of pendingCodes.keys()) {
    if (normalizeCode(code) === normalized) return code;
  }
  return null;
}

function findCodeBySessionId(sessionId: string): string | null {
  for (const [code, rec] of pendingCodes) {
    if (rec.sessionId === sessionId) return code;
  }
  return null;
}

// ─── Stripe API helpers (no SDK — raw HTTP to avoid deps) ───────────────────

async function stripeRequest(
  method: string,
  path: string,
  body?: Record<string, string>,
): Promise<any> {
  return new Promise((resolve, reject) => {
    const auth = Buffer.from(`${STRIPE_SECRET_KEY}:`).toString('base64');
    const bodyStr = body
      ? Object.entries(body).map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join('&')
      : '';

    const options: http.RequestOptions = {
      hostname: 'api.stripe.com',
      port: 443,
      path: `/v1${path}`,
      method,
      headers: {
        'Authorization': `Basic ${auth}`,
        'Content-Type': 'application/x-www-form-urlencoded',
        ...(bodyStr ? { 'Content-Length': Buffer.byteLength(bodyStr) } : {}),
      },
    };

    const req = https.request(options, (res) => {
      const chunks: Buffer[] = [];
      res.on('data', (chunk: Buffer) => chunks.push(chunk));
      res.on('end', () => {
        const text = Buffer.concat(chunks).toString('utf8');
        try {
          resolve(JSON.parse(text));
        } catch {
          reject(new Error(`Stripe response parse error: ${text.slice(0, 200)}`));
        }
      });
      res.on('error', reject);
    });
    req.on('error', reject);
    if (bodyStr) req.write(bodyStr);
    req.end();
  });
}

// ─── Webhook signature verification ─────────────────────────────────────────

function verifyStripeSignature(payload: string, sigHeader: string, secret: string): boolean {
  const elements = sigHeader.split(',');
  let timestamp = '';
  const signatures: string[] = [];

  for (const element of elements) {
    const [key, value] = element.split('=');
    if (key === 't') timestamp = value;
    if (key === 'v1') signatures.push(value);
  }

  if (!timestamp || signatures.length === 0) return false;

  const signedPayload = `${timestamp}.${payload}`;
  const expected = crypto
    .createHmac('sha256', secret)
    .update(signedPayload)
    .digest('hex');

  return signatures.some(sig => {
    try {
      return crypto.timingSafeEqual(Buffer.from(sig, 'hex'), Buffer.from(expected, 'hex'));
    } catch {
      return false;
    }
  });
}

// ─── License persistence ────────────────────────────────────────────────────

import * as fs from 'fs';

function loadLicenses(): void {
  try {
    if (fs.existsSync(licensesFile)) {
      const data = JSON.parse(fs.readFileSync(licensesFile, 'utf8'));
      for (const [k, v] of Object.entries(data)) {
        issuedLicenses.set(k, v as string);
      }
      console.log(`[License] Loaded ${issuedLicenses.size} licenses from disk`);
    }
  } catch (err) {
    console.warn(`[License] Failed to load licenses:`, err);
  }
}

function saveLicenses(): void {
  try {
    const data: Record<string, string> = {};
    for (const [k, v] of issuedLicenses) {
      data[k] = v;
    }
    fs.writeFileSync(licensesFile, JSON.stringify(data, null, 2));
  } catch (err) {
    console.warn(`[License] Failed to save licenses:`, err);
  }
}

function loadCodes(): void {
  try {
    if (fs.existsSync(codesFile)) {
      const data = JSON.parse(fs.readFileSync(codesFile, 'utf8'));
      for (const [k, v] of Object.entries(data)) {
        pendingCodes.set(k, v as PendingCode);
      }
      console.log(`[License] Loaded ${pendingCodes.size} pending codes from disk`);
    }
  } catch (err) {
    console.warn(`[License] Failed to load codes:`, err);
  }
}

function saveCodes(): void {
  try {
    const data: Record<string, PendingCode> = {};
    for (const [k, v] of pendingCodes) data[k] = v;
    fs.writeFileSync(codesFile, JSON.stringify(data, null, 2));
  } catch (err) {
    console.warn(`[License] Failed to save codes:`, err);
  }
}

function loadSubscriptions(): void {
  try {
    if (fs.existsSync(subscriptionsFile)) {
      const data = JSON.parse(fs.readFileSync(subscriptionsFile, 'utf8'));
      for (const [k, v] of Object.entries(data)) {
        subscriptions.set(k, v as SubRecord);
      }
      console.log(`[License] Loaded ${subscriptions.size} subscriptions from disk`);
    }
  } catch (err) {
    console.warn(`[License] Failed to load subscriptions:`, err);
  }
}

function saveSubscriptions(): void {
  try {
    const data: Record<string, SubRecord> = {};
    for (const [k, v] of subscriptions) data[k] = v;
    fs.writeFileSync(subscriptionsFile, JSON.stringify(data, null, 2));
  } catch (err) {
    console.warn(`[License] Failed to save subscriptions:`, err);
  }
}

function expireOldCodes(): void {
  const now = Date.now();
  let expired = 0;
  for (const [code, rec] of pendingCodes) {
    if (rec.expiresAt < now) {
      pendingCodes.delete(code);
      expired++;
    }
  }
  if (expired > 0) {
    console.log(`[License] Expired ${expired} unredeemed codes`);
    saveCodes();
  }
}

// ─── HTTP Server ────────────────────────────────────────────────────────────

function readBody(req: http.IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let size = 0;
    req.on('data', (chunk: Buffer) => {
      size += chunk.length;
      if (size > 1024 * 1024) { reject(new Error('Body too large')); return; }
      chunks.push(chunk);
    });
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });
}

function respond(res: http.ServerResponse, status: number, data: any): void {
  const json = JSON.stringify(data);
  res.writeHead(status, {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  });
  res.end(json);
}

async function handleRequest(req: http.IncomingMessage, res: http.ServerResponse): Promise<void> {
  const url = new URL(req.url || '/', `http://localhost:${PORT}`);

  // CORS preflight
  if (req.method === 'OPTIONS') {
    res.writeHead(204, {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    });
    res.end();
    return;
  }

  // ─── POST /checkout — Create a Stripe checkout session ─────────
  // No peerId in request — Stripe never sees the OpenDescent peer identity.
  if (req.method === 'POST' && url.pathname === '/checkout') {
    try {
      const session = await stripeRequest('POST', '/checkout/sessions', {
        'mode': 'subscription',
        'line_items[0][price]': STRIPE_PRICE_ID,
        'line_items[0][quantity]': '1',
        'success_url': `${process.env.LICENSE_URL || 'https://pay.open-descent.com'}/success?session_id={CHECKOUT_SESSION_ID}`,
        'cancel_url': `${process.env.LICENSE_URL || 'https://pay.open-descent.com'}/cancel`,
      });

      if (session.error) {
        console.error('[Stripe] Checkout session error:', session.error);
        respond(res, 500, { error: session.error.message });
        return;
      }

      respond(res, 200, { url: session.url, sessionId: session.id });
    } catch (err: any) {
      console.error('[Checkout] Error:', err);
      respond(res, 500, { error: err.message });
    }
    return;
  }

  // ─── POST /founder — Founder's Edition checkout ────────────────
  // No peerId in request. founder=true metadata is generic, not identifying.
  if (req.method === 'POST' && url.pathname === '/founder') {
    try {
      if (founderCount >= MAX_FOUNDERS) {
        respond(res, 400, { error: 'All Founder editions have been claimed' });
        return;
      }

      const session = await stripeRequest('POST', '/checkout/sessions', {
        'mode': 'payment',
        'line_items[0][price]': FOUNDER_PRICE_ID,
        'line_items[0][quantity]': '1',
        'metadata[founder]': 'true',
        'success_url': `${process.env.LICENSE_URL || 'https://pay.open-descent.com'}/success?session_id={CHECKOUT_SESSION_ID}`,
        'cancel_url': `${process.env.LICENSE_URL || 'https://pay.open-descent.com'}/cancel`,
      });

      if (session.error) {
        respond(res, 500, { error: session.error.message });
        return;
      }

      respond(res, 200, { url: session.url, sessionId: session.id });
    } catch (err: any) {
      respond(res, 500, { error: err.message });
    }
    return;
  }

  // ─── GET /turn-config — Serve TURN credentials ────────────────
  if (req.method === 'GET' && url.pathname === '/turn-config') {
    const turnHost = process.env.TURN_HOST || '188.166.151.203';
    const turnUser = process.env.TURN_USER || 'opendescent';
    const turnPass = process.env.TURN_PASS || '';
    const servers = [];
    if (turnPass) {
      servers.push(
        { urls: `turn:${turnHost}:3478`, username: turnUser, credential: turnPass },
        { urls: `turn:${turnHost}:3478?transport=tcp`, username: turnUser, credential: turnPass },
      );
    }
    respond(res, 200, { servers });
    return;
  }

  // ─── GET /founder-status — How many claimed ───────────────────
  if (req.method === 'GET' && url.pathname === '/founder-status') {
    respond(res, 200, { claimed: founderCount, total: MAX_FOUNDERS, remaining: MAX_FOUNDERS - founderCount });
    return;
  }

  // ─── POST /webhook — Stripe webhook ───────────────────────────
  if (req.method === 'POST' && url.pathname === '/webhook') {
    try {
      const body = await readBody(req);
      const sigHeader = req.headers['stripe-signature'] as string;

      // Verify webhook signature if secret is configured
      if (STRIPE_WEBHOOK_SECRET && sigHeader) {
        if (!verifyStripeSignature(body, sigHeader, STRIPE_WEBHOOK_SECRET)) {
          console.warn('[Webhook] Invalid signature');
          respond(res, 400, { error: 'Invalid signature' });
          return;
        }
      }

      const event = JSON.parse(body);
      console.log(`[Webhook] Received: ${event.type}`);

      if (event.type === 'checkout.session.completed') {
        const session = event.data.object;
        const isFounder = session.metadata?.founder === 'true';
        const subscriptionId: string | undefined = session.subscription || undefined;
        const sessionId: string = session.id;

        // Reuse code if /success already created one for this session
        let code = findCodeBySessionId(sessionId);
        if (!code) {
          code = generateCode();
          pendingCodes.set(code, {
            tier: 'pro',
            founder: isFounder,
            subscriptionId,
            sessionId,
            isRenewal: false,
            paidAt: Date.now(),
            expiresAt: Date.now() + CODE_EXPIRY_MS,
          });
          saveCodes();
        }
        if (isFounder) {
          founderCount++;
          console.log(`[License] FOUNDER code generated #${founderCount}/${MAX_FOUNDERS} (session ${sessionId.slice(0, 14)}...)`);
        } else {
          console.log(`[License] Pro code generated for session ${sessionId.slice(0, 14)}...`);
        }
      }

      // Subscription renewal — generate fresh license OR fresh code,
      // depending on whether the user picked standard or anonymous mode.
      if (event.type === 'invoice.paid') {
        const invoice = event.data.object;
        const subscriptionId: string | undefined = invoice.subscription || undefined;
        // Skip the first invoice for a brand-new subscription — that's covered
        // by checkout.session.completed above. `billing_reason` distinguishes.
        const isRenewal = invoice.billing_reason === 'subscription_cycle';

        if (subscriptionId && isRenewal) {
          const sub = subscriptions.get(subscriptionId);
          if (sub && !sub.anonymous && sub.peerId && LICENSE_PRIVATE_KEY) {
            // Standard mode: pre-sign a fresh license; app will pull via /sub-status
            const licenseKey = createLicense(sub.peerId, 'pro', LICENSE_DURATION_MS, LICENSE_PRIVATE_KEY);
            sub.latestLicense = licenseKey;
            saveSubscriptions();
            console.log(`[License] Renewed (standard) for sub ${subscriptionId.slice(0, 14)}...`);
          } else if (sub && sub.anonymous) {
            // Anonymous mode: generate a fresh code; app will pull via /sub-status
            const code = generateCode();
            pendingCodes.set(code, {
              tier: 'pro',
              founder: false,
              subscriptionId,
              isRenewal: true,
              paidAt: Date.now(),
              expiresAt: Date.now() + CODE_EXPIRY_MS,
            });
            // Replace any prior unredeemed renewal code for this sub
            if (sub.latestRenewalCode && pendingCodes.has(sub.latestRenewalCode)) {
              pendingCodes.delete(sub.latestRenewalCode);
            }
            sub.latestRenewalCode = code;
            saveCodes();
            saveSubscriptions();
            console.log(`[License] Renewed (anonymous) for sub ${subscriptionId.slice(0, 14)}...`);
          } else {
            // Subscription record not yet created — user hasn't redeemed initial code.
            // Replace their pending code with a fresh one so they don't redeem stale.
            for (const [code, rec] of pendingCodes) {
              if (rec.subscriptionId === subscriptionId && !rec.isRenewal) {
                pendingCodes.delete(code);
              }
            }
            const code = generateCode();
            pendingCodes.set(code, {
              tier: 'pro',
              founder: false,
              subscriptionId,
              isRenewal: true,
              paidAt: Date.now(),
              expiresAt: Date.now() + CODE_EXPIRY_MS,
            });
            saveCodes();
            console.log(`[License] Renewed (unredeemed sub) for sub ${subscriptionId.slice(0, 14)}...`);
          }
        }
      }

      // Cancellation / payment failure — drop the subscription record.
      if (event.type === 'customer.subscription.deleted' || event.type === 'invoice.payment_failed') {
        const obj = event.data.object;
        const subscriptionId: string | undefined = obj.id || obj.subscription;
        if (subscriptionId && subscriptions.has(subscriptionId)) {
          const sub = subscriptions.get(subscriptionId)!;
          if (sub.latestRenewalCode) pendingCodes.delete(sub.latestRenewalCode);
          subscriptions.delete(subscriptionId);
          saveSubscriptions();
          saveCodes();
          console.log(`[License] Revoked subscription ${subscriptionId.slice(0, 14)}...`);
        }
      }

      respond(res, 200, { received: true });
    } catch (err: any) {
      console.error('[Webhook] Error:', err);
      respond(res, 500, { error: err.message });
    }
    return;
  }

  // ─── POST /redeem — Redeem a code for a signed license ────────
  // Body: { code, peerId, anonymous?: boolean }
  // Server signs a license bound to peerId. Stripe never sees peerId.
  // anonymous=true: server forgets peerId after activation; future renewals
  //                 produce codes (delivered via /sub-status), not licenses.
  // anonymous=false (default): server stores subId→peerId for seamless renewals.
  if (req.method === 'POST' && url.pathname === '/redeem') {
    try {
      if (!LICENSE_PRIVATE_KEY) {
        respond(res, 500, { error: 'License signing not configured' });
        return;
      }

      const body = await readBody(req);
      const { code, peerId, anonymous } = JSON.parse(body);

      if (!code || typeof code !== 'string') {
        respond(res, 400, { error: 'Missing code' });
        return;
      }
      if (!peerId || typeof peerId !== 'string' || peerId.length > 256) {
        respond(res, 400, { error: 'Missing or invalid peerId' });
        return;
      }

      const normalized = normalizeCode(code);
      const realCode = findCodeByNormalized(normalized);
      if (!realCode) {
        respond(res, 404, { error: 'Code not found, already redeemed, or expired' });
        return;
      }

      const rec = pendingCodes.get(realCode)!;
      if (rec.expiresAt < Date.now()) {
        pendingCodes.delete(realCode);
        saveCodes();
        respond(res, 410, { error: 'Code expired' });
        return;
      }

      const duration = rec.founder ? FOUNDER_DURATION_MS : LICENSE_DURATION_MS;
      const licenseKey = createLicense(peerId, 'pro', duration, LICENSE_PRIVATE_KEY, rec.founder);

      // Manage subscription record (subscriptions only — founder one-shot has no subId)
      if (rec.subscriptionId) {
        const existing = subscriptions.get(rec.subscriptionId);
        if (existing) {
          // Renewal redemption — update record (mode may have changed if user reactivates)
          existing.anonymous = !!anonymous;
          existing.peerId = anonymous ? undefined : peerId;
          existing.latestLicense = anonymous ? undefined : licenseKey;
          existing.latestRenewalCode = undefined;
        } else {
          // First redemption — create record
          subscriptions.set(rec.subscriptionId, {
            anonymous: !!anonymous,
            peerId: anonymous ? undefined : peerId,
            latestLicense: anonymous ? undefined : licenseKey,
            founder: rec.founder,
            createdAt: Date.now(),
          });
        }
        saveSubscriptions();
      }

      pendingCodes.delete(realCode);
      saveCodes();
      console.log(`[License] Redeemed code (${anonymous ? 'anon' : 'standard'}, founder=${rec.founder}) → ${peerId.slice(0, 12)}...`);

      respond(res, 200, {
        licenseKey,
        subscriptionId: rec.subscriptionId,
        founder: rec.founder,
      });
    } catch (err: any) {
      console.error('[Redeem] Error:', err);
      respond(res, 500, { error: err.message });
    }
    return;
  }

  // ─── GET /sub-status?subId=... — Poll for renewal license/code ─
  // App calls this on startup or "Refresh license" button. Returns:
  //   - { licenseKey } if standard mode and a renewal license is waiting
  //   - { renewalCode } if anonymous mode and a renewal code is waiting
  //   - { status: 'current' } if no renewal pending
  //   - 404 if subscription unknown / cancelled
  if (req.method === 'GET' && url.pathname === '/sub-status') {
    const subId = url.searchParams.get('subId');
    if (!subId) {
      respond(res, 400, { error: 'Missing subId' });
      return;
    }
    const sub = subscriptions.get(subId);
    if (!sub) {
      respond(res, 404, { error: 'Subscription not found or cancelled' });
      return;
    }
    if (!sub.anonymous && sub.latestLicense) {
      const licenseKey = sub.latestLicense;
      sub.latestLicense = undefined;
      saveSubscriptions();
      respond(res, 200, { licenseKey });
      return;
    }
    if (sub.anonymous && sub.latestRenewalCode && pendingCodes.has(sub.latestRenewalCode)) {
      respond(res, 200, { renewalCode: sub.latestRenewalCode });
      return;
    }
    respond(res, 200, { status: 'current' });
    return;
  }

  // ─── GET /license?peerId=... — Retrieve license key (LEGACY) ──
  // Kept for backward compat with pre-redemption-flow customers.
  // New customers use POST /redeem.
  if (req.method === 'GET' && url.pathname === '/license') {
    const peerId = url.searchParams.get('peerId');
    if (!peerId) {
      respond(res, 400, { error: 'Missing peerId' });
      return;
    }

    const licenseKey = issuedLicenses.get(peerId);
    if (licenseKey) {
      respond(res, 200, { licenseKey });
    } else {
      respond(res, 404, { error: 'No license found for this peer' });
    }
    return;
  }

  // ─── GET /success — Post-checkout success page ────────────────
  // Displays a redemption code, NOT a license key. Stripe never sees the
  // user's peerId, so we can't sign a license here. The user redeems the
  // code in the app, where their peerId is local.
  if (req.method === 'GET' && url.pathname === '/success') {
    const sessionId = url.searchParams.get('session_id');
    let code = '';
    let isFounderCode = false;

    if (sessionId) {
      try {
        // Fall back to creating the code here if the webhook hasn't arrived yet
        let realCode = findCodeBySessionId(sessionId);
        if (!realCode) {
          const session = await stripeRequest('GET', `/checkout/sessions/${sessionId}`);
          if (session && session.payment_status === 'paid') {
            const sessionFounder = session.metadata?.founder === 'true';
            const subscriptionId: string | undefined = session.subscription || undefined;
            realCode = generateCode();
            pendingCodes.set(realCode, {
              tier: 'pro',
              founder: sessionFounder,
              subscriptionId,
              sessionId,
              isRenewal: false,
              paidAt: Date.now(),
              expiresAt: Date.now() + CODE_EXPIRY_MS,
            });
            if (sessionFounder) founderCount++;
            saveCodes();
          }
        }
        if (realCode) {
          code = realCode;
          isFounderCode = pendingCodes.get(realCode)?.founder === true;
        }
      } catch (err) {
        console.error('[Success] Failed to retrieve session:', err);
      }
    }

    const html = `<!DOCTYPE html>
<html><head><title>OpenDescent Pro — ${isFounderCode ? "Founder's Edition" : 'Activated'}</title>
<style>
  body { font-family: -apple-system, sans-serif; background: #212121; color: #EEEEEE;
         display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
  .card { background: #262626; border: 1px solid rgba(13,115,119,0.2); border-radius: 6px; padding: 2rem;
          max-width: 600px; width: 90%; text-align: center; }
  h1 { color: #32E0C4; margin-bottom: 0.5rem; }
  .code-box { background: #0d1117; border: 1px solid #30363d; border-radius: 8px; padding: 1.2rem;
              margin: 1.5rem 0; font-family: monospace; font-size: 1.4rem; letter-spacing: 2px;
              user-select: all; cursor: pointer; color: #ffd166; font-weight: 700; }
  .hint { color: #8b949e; font-size: 0.9rem; }
  .small { color: #6e7681; font-size: 0.78rem; margin-top: 1rem; }
  .copy-btn { background: #238636; color: #fff; border: none; padding: 0.6rem 1.5rem;
              border-radius: 6px; cursor: pointer; font-size: 1rem; margin-top: 0.5rem; }
  .copy-btn:hover { background: #2ea043; }
  ol { text-align: left; color: #c9d1d9; font-size: 0.95rem; line-height: 1.7; padding-left: 1.2rem; }
</style></head>
<body><div class="card">
  <h1>${isFounderCode ? "Welcome, Founder." : "Welcome to Pro!"}</h1>
  <p>${isFounderCode ? "You're one of the first 101. Lifetime Pro access — every Pro feature, forever. Thank you for believing early." : "Your OpenDescent Pro subscription is active."}</p>
  ${code ? `
    <p class="hint">Your redemption code:</p>
    <div class="code-box" id="code" onclick="copyCode()">${code}</div>
    <button class="copy-btn" onclick="copyCode()">Copy Code</button>
    <p class="hint" id="copied" style="display:none; color: #7ee787;">Copied!</p>
    <ol style="margin-top:1.5rem">
      <li>Open OpenDescent</li>
      <li>Settings → <strong>Redeem Code</strong></li>
      <li>Paste this code and click Activate</li>
    </ol>
    <p class="small">Stripe never sees your peer ID. The code is the only thing linking your payment to your activation, and it's deleted on redemption.</p>
  ` : `
    <p class="hint">Your code is being generated. Refresh this page in a moment.</p>
  `}
</div>
<script>
function copyCode() {
  navigator.clipboard.writeText(document.getElementById('code').textContent);
  document.getElementById('copied').style.display = 'block';
}
</script></body></html>`;

    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(html);
    return;
  }

  // ─── GET /cancel — Checkout cancelled ─────────────────────────
  if (req.method === 'GET' && url.pathname === '/cancel') {
    const html = `<!DOCTYPE html>
<html><head><title>OpenDescent — Checkout Cancelled</title>
<style>
  body { font-family: -apple-system, sans-serif; background: #0d1117; color: #e6edf3;
         display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
  .card { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 2rem;
          max-width: 400px; text-align: center; }
  a { color: #58a6ff; }
</style></head>
<body><div class="card">
  <h2>Checkout cancelled</h2>
  <p>No charge was made. You can close this tab and try again anytime from the app.</p>
</div></body></html>`;

    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(html);
    return;
  }

  // ─── Fallback ─────────────────────────────────────────────────
  respond(res, 404, { error: 'Not found' });
}

// ─── Main ───────────────────────────────────────────────────────────────────

function main(): void {
  // Validate required config
  if (!STRIPE_SECRET_KEY) {
    console.error('ERROR: STRIPE_SECRET_KEY environment variable required');
    process.exit(1);
  }

  if (!LICENSE_PRIVATE_KEY) {
    console.log('[License] No LICENSE_PRIVATE_KEY set. Generating a new keypair...');
    const keypair = generateLicenseKeypair();
    console.log('\n=== SAVE THESE KEYS ===');
    console.log(`LICENSE_PUBLIC_KEY=${keypair.publicKey}`);
    console.log(`LICENSE_PRIVATE_KEY=${keypair.privateKey}`);
    console.log('======================\n');
    console.log('Set these as environment variables and restart.');
    console.log('The PUBLIC key must be embedded in the client (src/licensing/license.ts).');
    process.exit(0);
  }

  loadLicenses();
  loadCodes();
  loadSubscriptions();

  // Backfill founderCount from any redeemed founder subs and any pending founder codes,
  // so a server restart doesn't oversell.
  founderCount = 0;
  for (const sub of subscriptions.values()) if (sub.founder) founderCount++;
  for (const rec of pendingCodes.values()) if (rec.founder) founderCount++;
  console.log(`[License] Founder slots used: ${founderCount}/${MAX_FOUNDERS}`);

  // Sweep expired codes hourly
  setInterval(expireOldCodes, 60 * 60 * 1000);
  expireOldCodes();

  const server = http.createServer((req, res) => {
    handleRequest(req, res).catch((err) => {
      console.error('[Server] Unhandled error:', err);
      respond(res, 500, { error: 'Internal server error' });
    });
  });

  server.listen(PORT, '0.0.0.0', () => {
    console.log(`[License Server] Running on port ${PORT}`);
    console.log(`[License Server] Checkout:    POST http://localhost:${PORT}/checkout`);
    console.log(`[License Server] Founder:     POST http://localhost:${PORT}/founder`);
    console.log(`[License Server] Redeem:      POST http://localhost:${PORT}/redeem`);
    console.log(`[License Server] Sub-status:  GET  http://localhost:${PORT}/sub-status?subId=...`);
    console.log(`[License Server] Webhook:     POST http://localhost:${PORT}/webhook`);
    console.log(`[License Server] Legacy:      GET  http://localhost:${PORT}/license?peerId=...`);
  });
}

main();
