/**
 * Network Node — Core libp2p node setup and management
 *
 * Each running instance creates one of these nodes. It handles:
 * - Peer discovery (mDNS for local, DHT for global, bootstrap for initial)
 * - Encrypted connections between peers (Noise protocol)
 * - Stream multiplexing (Yamux)
 * - NAT traversal via circuit relay
 * - Custom protocol handlers
 * - Automatic profile exchange on connect (so peers get each other's encryption keys)
 *
 * Two ID systems are bridged here:
 * - libp2p PeerId: generated by libp2p from its own keys (e.g., 12D3KooW...)
 * - DecentraNet PeerId: base58 hash of our Ed25519 public key (e.g., 2q69Pfh...)
 * Users interact with DecentraNet PeerIds; libp2p PeerIds are internal plumbing.
 */

import { createLibp2p, type Libp2p } from 'libp2p';
import { tcp } from '@libp2p/tcp';
import { webSockets } from '@libp2p/websockets';
import { noise } from '@chainsafe/libp2p-noise';
import { yamux } from '@chainsafe/libp2p-yamux';
import { mdns } from '@libp2p/mdns';
import { kadDHT } from '@libp2p/kad-dht';
import { bootstrap } from '@libp2p/bootstrap';
import { identify } from '@libp2p/identify';
import { dcutr } from '@libp2p/dcutr';
import { circuitRelayTransport, circuitRelayServer } from '@libp2p/circuit-relay-v2';

import { multiaddr } from '@multiformats/multiaddr';
import type { NodeConfig, Identity, PeerProfile, NetworkEvent, NetworkEventType } from '../types/index.js';
import { generateIdentity, loadIdentity, saveIdentity, publicKeyToPeerId, createPeerProfile, verifyPeerProfile } from '../crypto/identity.js';

/** Default bootstrap peers for the DecentraNet network */
const DEFAULT_BOOTSTRAP_PEERS: string[] = [
  '/ip4/188.166.151.203/tcp/6001/p2p/12D3KooWStM6ett7nNXKdSy7kTqxdYmYni2jcmvNSpAs9Pbfo1tA',
  '/ip4/188.166.151.203/tcp/6002/ws/p2p/12D3KooWStM6ett7nNXKdSy7kTqxdYmYni2jcmvNSpAs9Pbfo1tA',
];

const PROTOCOL_PREFIX = '/decentranet';
export const PROTOCOLS = {
  MESSAGE: `${PROTOCOL_PREFIX}/message/1.0.0`,
  SHARD_STORE: `${PROTOCOL_PREFIX}/shard-store/1.0.0`,
  SHARD_RETRIEVE: `${PROTOCOL_PREFIX}/shard-retrieve/1.0.0`,
  CALL_SIGNAL: `${PROTOCOL_PREFIX}/call-signal/1.0.0`,
  PEER_EXCHANGE: `${PROTOCOL_PREFIX}/peer-exchange/1.0.0`,
  ACCOUNT_BUNDLE: `${PROTOCOL_PREFIX}/account-bundle/1.0.0`,
  HISTORY_SYNC: `${PROTOCOL_PREFIX}/history-sync/1.0.0`,
} as const;

type EventHandler = (event: NetworkEvent) => void;

export class DecentraNode {
  private node: Libp2p | null = null;
  private config: NodeConfig;
  private identity: Identity;
  private eventHandlers: Map<NetworkEventType, EventHandler[]> = new Map();

  // Peer tracking: bridge between libp2p PeerIds and DecentraNet PeerIds
  private knownPeers: Map<string, PeerProfile> = new Map();        // decentraId -> profile
  private libp2pToDecentra: Map<string, string> = new Map();       // libp2pId -> decentraId
  private decentraToLibp2p: Map<string, string> = new Map();       // decentraId -> libp2pId
  private exchangeInProgress: Set<string> = new Set();              // libp2pIds currently exchanging
  private shardRetrieveHandler?: (shardId: string) => Promise<Uint8Array | null>;
  private bundleStoreHandler?: (peerId: string, data: string) => Promise<void>;
  private bundleRetrieveHandler?: (peerId: string) => Promise<string | null>;
  private historySyncHandler?: (requesterId: string, since: number) => Promise<Uint8Array | null>;
  private tofuHandler?: (peerId: string, publicKey: Uint8Array) => Promise<boolean>;
  private passphrase: string;

  // Rate limiting: 100 messages per 60-second window per peer
  private rateLimiter: Map<string, { count: number; windowStart: number }> = new Map();
  private rateLimitCleanupTimer?: ReturnType<typeof setInterval>;

  constructor(config: NodeConfig, passphrase: string) {
    this.passphrase = passphrase;
    this.config = config;

    try {
      this.identity = loadIdentity(config.identityPath, passphrase);
      console.log(`[Identity] Loaded existing identity`);
    } catch {
      console.log(`[Identity] Generating new identity...`);
      this.identity = generateIdentity(config.displayName);
      saveIdentity(this.identity, config.identityPath, passphrase);
    }

    console.log(`[Identity] Peer ID: ${this.getPeerId()}`);
    if (this.identity.displayName) {
      console.log(`[Identity] Display name: ${this.identity.displayName}`);
    }
  }

  async start(): Promise<void> {
    const wsPort = this.config.wsPort || this.config.port + 1;
    const isPublic = this.config.isPublic || false;

    console.log(`[Node] Starting on TCP:${this.config.port} WS:${wsPort}${isPublic ? ' (PUBLIC mode)' : ''}...`);

    // Merge default + user-supplied bootstrap peers
    const allBootstrapPeers = [
      ...DEFAULT_BOOTSTRAP_PEERS,
      ...this.config.bootstrapPeers,
    ].filter((addr, i, arr) => arr.indexOf(addr) === i); // dedupe

    // If an announce IP is set (e.g., public VPS IP), advertise those addresses
    const announce: string[] = [];
    if (this.config.announceIp) {
      announce.push(`/ip4/${this.config.announceIp}/tcp/${this.config.port}`);
      announce.push(`/ip4/${this.config.announceIp}/tcp/${wsPort}/ws`);
    }

    const libp2pConfig: any = {
      addresses: {
        listen: [
          `/ip4/0.0.0.0/tcp/${this.config.port}`,
          `/ip4/0.0.0.0/tcp/${wsPort}/ws`,
        ],
        ...(announce.length > 0 ? { announce } : {}),
      },
      transports: [
        tcp(),
        webSockets(),
        circuitRelayTransport({ reservationConcurrency: 1 }),
      ],
      connectionEncrypters: [noise()],
      streamMuxers: [yamux()],
      services: {
        identify: identify(),
        dht: kadDHT({
          protocol: '/decentranet/kad/1.0.0',
          clientMode: !isPublic,
        }),
        dcutr: dcutr(),
      },
      peerDiscovery: [mdns()],
    };

    if (allBootstrapPeers.length > 0) {
      libp2pConfig.peerDiscovery.push(
        bootstrap({ list: allBootstrapPeers })
      );
    }

    // Public nodes always run the relay server; private nodes only if configured
    if (isPublic || this.config.enableRelay) {
      libp2pConfig.services.relay = circuitRelayServer();
    }

    this.node = await createLibp2p(libp2pConfig);
    this.setupEventListeners();
    await this.registerProtocolHandlers();
    await this.node.start();

    // Clean stale rate limit entries every 5 minutes
    this.rateLimitCleanupTimer = setInterval(() => this.cleanRateLimiter(), 5 * 60 * 1000);

    const addresses = this.node.getMultiaddrs();
    console.log(`[Node] Listening on:`);
    addresses.forEach((addr) => console.log(`  ${addr.toString()}`));

    if (isPublic) {
      console.log(`[Node] PUBLIC mode — this node is a DHT server and circuit relay`);
    } else {
      console.log(`[Node] DHT client mode (behind NAT). Use --public on public-facing nodes.`);
    }

    console.log(`[Node] Node started successfully`);
  }

  async stop(): Promise<void> {
    if (this.rateLimitCleanupTimer) {
      clearInterval(this.rateLimitCleanupTimer);
      this.rateLimitCleanupTimer = undefined;
    }
    if (this.node) {
      console.log(`[Node] Shutting down...`);
      await this.node.stop();
      console.log(`[Node] Stopped`);
    }
  }

  // ─── Identity & Addressing ──────────────────────────────────────────────

  getPeerId(): string {
    return publicKeyToPeerId(this.identity.publicKey);
  }

  getLibp2pPeerId(): string {
    if (!this.node) throw new Error('Node not started');
    return this.node.peerId.toString();
  }

  getLibp2p(): Libp2p {
    if (!this.node) throw new Error('Node not started');
    return this.node;
  }

  getIdentity(): Identity {
    return this.identity;
  }

  getAddresses(): string[] {
    if (!this.node) return [];
    return this.node.getMultiaddrs().map((addr) => addr.toString());
  }

  getProfile(): PeerProfile {
    return createPeerProfile(this.identity, this.getAddresses());
  }

  setDisplayName(name: string): void {
    this.identity.displayName = name;
    saveIdentity(this.identity, this.config.identityPath, this.passphrase);
  }

  // ─── Peer Management ────────────────────────────────────────────────────

  /** Get all connected libp2p peer IDs */
  getConnectedLibp2pPeers(): string[] {
    if (!this.node) return [];
    return this.node.getPeers().map((p) => p.toString());
  }

  /** Get all connected peers with their DecentraNet profiles (only exchanged ones) */
  getConnectedPeers(): { libp2pId: string; decentraId?: string; profile?: PeerProfile }[] {
    const libp2pPeers = this.getConnectedLibp2pPeers();
    return libp2pPeers.map((libp2pId) => {
      const decentraId = this.libp2pToDecentra.get(libp2pId);
      return {
        libp2pId,
        decentraId,
        profile: decentraId ? this.knownPeers.get(decentraId) : undefined,
      };
    });
  }

  /** Get a peer profile by DecentraNet PeerId */
  getKnownPeer(decentraId: string): PeerProfile | undefined {
    return this.knownPeers.get(decentraId);
  }

  /** Get all known peer profiles */
  getAllKnownPeers(): PeerProfile[] {
    return Array.from(this.knownPeers.values());
  }

  /** Manually register a peer profile (e.g., from storage on startup) */
  registerKnownPeer(profile: PeerProfile, libp2pId?: string): void {
    this.knownPeers.set(profile.peerId, profile);
    if (libp2pId) {
      this.libp2pToDecentra.set(libp2pId, profile.peerId);
      this.decentraToLibp2p.set(profile.peerId, libp2pId);
    }
  }

  /** Resolve a DecentraNet PeerId to a libp2p PeerId */
  resolveDecentraId(decentraId: string): string | undefined {
    return this.decentraToLibp2p.get(decentraId);
  }

  /** Resolve a libp2p PeerId to a DecentraNet PeerId */
  resolveLibp2pId(libp2pId: string): string | undefined {
    return this.libp2pToDecentra.get(libp2pId);
  }

  /** Check if a peer has exceeded the rate limit (100 msg / 60s) */
  private isRateLimited(peerId: string): boolean {
    const now = Date.now();
    const entry = this.rateLimiter.get(peerId);

    if (!entry || now - entry.windowStart > 60_000) {
      this.rateLimiter.set(peerId, { count: 1, windowStart: now });
      return false;
    }

    entry.count++;
    if (entry.count > 100) {
      console.warn(`[RateLimit] Peer ${peerId} exceeded 100 msg/60s — dropping message`);
      return true;
    }
    return false;
  }

  /** Remove stale rate limit entries older than 2 minutes */
  private cleanRateLimiter(): void {
    const cutoff = Date.now() - 120_000;
    for (const [peerId, entry] of this.rateLimiter) {
      if (entry.windowStart < cutoff) {
        this.rateLimiter.delete(peerId);
      }
    }
  }

  /** Register a handler to serve shard retrieve requests */
  setShardRetrieveHandler(handler: (shardId: string) => Promise<Uint8Array | null>): void {
    this.shardRetrieveHandler = handler;
  }

  /** Register handlers for account bundle store/retrieve */
  setBundleHandlers(
    store: (peerId: string, data: string) => Promise<void>,
    retrieve: (peerId: string) => Promise<string | null>,
  ): void {
    this.bundleStoreHandler = store;
    this.bundleRetrieveHandler = retrieve;
  }

  /** Register a handler for history sync requests */
  setHistorySyncHandler(handler: (requesterId: string, since: number) => Promise<Uint8Array | null>): void {
    this.historySyncHandler = handler;
  }

  /**
   * Register a TOFU handler. Called during profile exchange.
   * Returns true if the key is trusted (first-seen or matches pin), false if changed.
   */
  setTofuHandler(handler: (peerId: string, publicKey: Uint8Array) => Promise<boolean>): void {
    this.tofuHandler = handler;
  }

  /** Find a peer by display name (partial match, prefers connected peers) */
  findPeerByName(name: string): PeerProfile | undefined {
    const lower = name.toLowerCase();
    const connectedDecentraIds = new Set(
      this.getConnectedLibp2pPeers()
        .map((id) => this.libp2pToDecentra.get(id))
        .filter(Boolean)
    );

    let fallback: PeerProfile | undefined;
    for (const profile of this.knownPeers.values()) {
      if (profile.displayName?.toLowerCase().includes(lower)) {
        if (connectedDecentraIds.has(profile.peerId)) return profile;
        if (!fallback) fallback = profile;
      }
    }
    return fallback;
  }

  // ─── Invite Codes ──────────────────────────────────────────────────────

  /**
   * Generate a base64url invite code containing our multiaddrs and identity.
   * Other peers can use this to connect to us directly.
   */
  getInviteCode(): string {
    const addrs = this.getAddresses()
      // Filter out loopback/localhost — not useful for remote peers
      .filter((a) => !a.includes('/127.0.0.1/') && !a.includes('/::1/'));

    const payload = {
      v: 1,
      a: addrs,
      d: this.getPeerId(),
      n: this.identity.displayName || undefined,
    };

    const json = JSON.stringify(payload);
    // base64url: standard base64 with + -> -, / -> _, strip =
    const b64 = Buffer.from(json).toString('base64')
      .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    return b64;
  }

  /**
   * Connect to a peer using their invite code.
   * Decodes the code, dials their multiaddrs, and returns their DecentraNet ID on success.
   */
  async connectWithInvite(code: string): Promise<{ peerId: string; name?: string }> {
    if (!this.node) throw new Error('Node not started');

    // Decode base64url
    const padded = code.replace(/-/g, '+').replace(/_/g, '/');
    const json = Buffer.from(padded, 'base64').toString('utf-8');

    let payload: { v: number; a: string[]; d: string; n?: string };
    try {
      payload = JSON.parse(json);
    } catch {
      throw new Error('Invalid invite code — could not parse');
    }

    if (!payload.v || !payload.a || !payload.d) {
      throw new Error('Invalid invite code — missing fields');
    }

    console.log(`[Invite] Connecting to ${payload.n || payload.d}...`);
    console.log(`[Invite] Trying ${payload.a.length} address(es)`);

    // Try each multiaddr in order
    let connected = false;
    for (const addr of payload.a) {
      try {
        console.log(`[Invite] Dialing ${addr}...`);
        await this.node.dial(multiaddr(addr));
        connected = true;
        console.log(`[Invite] Connected via ${addr}`);
        break;
      } catch (error: any) {
        console.log(`[Invite] Failed: ${addr} (${error.message || error.code || 'unknown'})`);
      }
    }

    if (!connected) {
      throw new Error('Could not connect to any of the peer\'s addresses');
    }

    return { peerId: payload.d, name: payload.n };
  }

  // ─── Events ─────────────────────────────────────────────────────────────

  on(event: NetworkEventType, handler: EventHandler): void {
    const handlers = this.eventHandlers.get(event) || [];
    handlers.push(handler);
    this.eventHandlers.set(event, handlers);
  }

  private emit(type: NetworkEventType, data?: unknown, peerId?: string): void {
    const event: NetworkEvent = { type, data, peerId, timestamp: Date.now() };
    const handlers = this.eventHandlers.get(type) || [];
    handlers.forEach((h) => h(event));
  }

  // ─── Communication ──────────────────────────────────────────────────────

  /**
   * Send data to a peer identified by their DecentraNet PeerId.
   * Resolves the DecentraNet ID to a libp2p connection and sends.
   */
  async sendToPeer(decentraId: string, protocol: string, data: Uint8Array): Promise<Uint8Array | null> {
    const libp2pId = this.decentraToLibp2p.get(decentraId);
    if (!libp2pId) {
      console.log(`[Node] Unknown DecentraNet peer ${decentraId} — no libp2p mapping`);
      return null;
    }
    return this.sendToLibp2pPeer(libp2pId, protocol, data);
  }

  /**
   * Send data to a peer identified by their libp2p PeerId.
   */
  async sendToLibp2pPeer(libp2pId: string, protocol: string, data: Uint8Array): Promise<Uint8Array | null> {
    if (!this.node) throw new Error('Node not started');

    try {
      const connections = this.node.getConnections();
      const conn = connections.find((c) => c.remotePeer.toString() === libp2pId);

      if (!conn) {
        console.log(`[Node] No active connection to ${libp2pId}`);
        return null;
      }

      const stream = await this.node.dialProtocol(conn.remotePeer, protocol);

      // Write request
      await stream.sink((async function* () {
        yield data;
      })());

      // Read response
      const chunks: Uint8Array[] = [];
      for await (const chunk of stream.source) {
        chunks.push(chunk.subarray());
      }

      return chunks.length > 0 ? concatenateUint8Arrays(chunks) : null;
    } catch (error: any) {
      const msg = error?.message || error?.code || String(error);
      // Suppress noisy connection errors (dead peers, EOF, reset)
      if (msg.includes('EOF') || msg.includes('ECONNRESET') || msg.includes('stream ended')) {
        console.log(`[Node] Connection to ${libp2pId} lost (${error?.code || 'EOF'})`);
      } else {
        console.error(`[Node] Failed to send to ${libp2pId}:`, msg);
      }
      return null;
    }
  }

  // ─── Profile Exchange ───────────────────────────────────────────────────

  /**
   * Initiate a profile exchange with a connected libp2p peer.
   * Sends our profile and receives theirs. Called automatically on connect.
   */
  private async initiateProfileExchange(libp2pId: string): Promise<void> {
    if (this.exchangeInProgress.has(libp2pId)) return;
    this.exchangeInProgress.add(libp2pId);

    try {
      const ourProfile = this.getProfile();
      const profileData = serializeProfile(ourProfile);
      const data = new TextEncoder().encode(JSON.stringify(profileData));

      const response = await this.sendToLibp2pPeer(libp2pId, PROTOCOLS.PEER_EXCHANGE, data);

      if (response) {
        const theirProfileData = JSON.parse(new TextDecoder().decode(response));
        const theirProfile = deserializeProfile(theirProfileData);

        if (verifyPeerProfile(theirProfile)) {
          // TOFU check
          if (this.tofuHandler) {
            const trusted = await this.tofuHandler(theirProfile.peerId, theirProfile.publicKey);
            if (!trusted) {
              console.warn(`[TOFU] Key change detected for ${theirProfile.peerId}! Peer not auto-accepted.`);
              this.emit('peer:key_changed', {
                peerId: theirProfile.peerId,
                displayName: theirProfile.displayName,
              }, theirProfile.peerId);
            }
          }
          this.registerKnownPeer(theirProfile, libp2pId);
          const name = theirProfile.displayName || theirProfile.peerId.slice(0, 12);
          console.log(`[Exchange] Received profile from ${name} (${theirProfile.peerId})`);
          this.emit('peer:connected', theirProfile, theirProfile.peerId);
        } else {
          console.warn(`[Exchange] Profile from ${libp2pId} failed signature verification`);
        }
      }
    } catch (error) {
      console.error(`[Exchange] Failed with ${libp2pId}:`, error);
    } finally {
      this.exchangeInProgress.delete(libp2pId);
    }
  }

  // ─── Private Setup ──────────────────────────────────────────────────────

  private setupEventListeners(): void {
    if (!this.node) return;

    this.node.addEventListener('peer:connect', (event) => {
      const libp2pId = event.detail.toString();
      console.log(`[Node] Peer connected: ${libp2pId}`);
      // Auto-exchange profiles after a short delay (let the connection stabilize)
      setTimeout(() => this.initiateProfileExchange(libp2pId), 500);
    });

    this.node.addEventListener('peer:disconnect', (event) => {
      const libp2pId = event.detail.toString();
      const decentraId = this.libp2pToDecentra.get(libp2pId);
      console.log(`[Node] Peer disconnected: ${libp2pId}${decentraId ? ` (${decentraId})` : ''}`);
      this.emit('peer:disconnected', undefined, decentraId || libp2pId);
    });

    // Log when relay circuit addresses are acquired
    this.node.addEventListener('self:peer:update', () => {
      if (!this.node) return;
      const relayAddrs = this.node.getMultiaddrs()
        .filter((a) => a.toString().includes('/p2p-circuit/'));
      if (relayAddrs.length > 0) {
        console.log(`[Relay] Circuit relay addresses available:`);
        relayAddrs.forEach((a) => console.log(`  ${a.toString()}`));
      }
    });

    this.node.addEventListener('peer:discovery', async (event) => {
      const peerInfo = event.detail;
      const libp2pId = peerInfo.id.toString();
      console.log(`[Node] Discovered peer: ${libp2pId}`);

      // Auto-dial discovered peers if we're not already connected
      if (!this.node) return;
      const existingConns = this.node.getConnections().filter(
        (c) => c.remotePeer.toString() === libp2pId
      );
      if (existingConns.length === 0) {
        try {
          console.log(`[Node] Dialing discovered peer ${libp2pId}...`);
          await this.node.dial(peerInfo.id);
        } catch (error) {
          // Dial failures are expected (e.g., peer went offline)
          console.log(`[Node] Could not dial ${libp2pId}`);
        }
      }
    });
  }

  private async registerProtocolHandlers(): Promise<void> {
    if (!this.node) return;

    // Peer exchange: receive their profile, send ours back
    await this.node.handle(PROTOCOLS.PEER_EXCHANGE, async ({ stream, connection }) => {
      const libp2pId = connection.remotePeer.toString();
      try {
        const data = await readFromSource(stream.source);
        const theirProfileData = JSON.parse(new TextDecoder().decode(data));
        const theirProfile = deserializeProfile(theirProfileData);

        if (verifyPeerProfile(theirProfile)) {
          // TOFU check
          if (this.tofuHandler) {
            const trusted = await this.tofuHandler(theirProfile.peerId, theirProfile.publicKey);
            if (!trusted) {
              console.warn(`[TOFU] Key change detected for ${theirProfile.peerId}!`);
              this.emit('peer:key_changed', {
                peerId: theirProfile.peerId,
                displayName: theirProfile.displayName,
              }, theirProfile.peerId);
            }
          }
          this.registerKnownPeer(theirProfile, libp2pId);
          const name = theirProfile.displayName || theirProfile.peerId.slice(0, 12);
          console.log(`[Exchange] Received profile from ${name} (${theirProfile.peerId})`);
          this.emit('peer:connected', theirProfile, theirProfile.peerId);
        } else {
          console.warn(`[Exchange] Profile from ${libp2pId} failed verification`);
        }

        // Send our profile back
        const ourProfile = this.getProfile();
        const responseData = new TextEncoder().encode(JSON.stringify(serializeProfile(ourProfile)));
        await writeToSink(stream, responseData);
      } catch (error) {
        console.error(`[Exchange] Error handling profile exchange:`, error);
      }
    });

    // Message delivery
    await this.node.handle(PROTOCOLS.MESSAGE, async ({ stream, connection }) => {
      const libp2pId = connection.remotePeer.toString();
      if (this.isRateLimited(libp2pId)) { try { await stream.close(); } catch {} return; }
      const decentraId = this.libp2pToDecentra.get(libp2pId);
      try {
        const data = await readFromSource(stream.source);
        this.emit('message:received', data, decentraId || libp2pId);
        await writeToSink(stream, new TextEncoder().encode('ACK'));
      } catch (error) {
        console.error(`[Protocol] Error handling message:`, error);
      }
    });

    // Shard storage
    await this.node.handle(PROTOCOLS.SHARD_STORE, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        this.emit('shard:stored', data, connection.remotePeer.toString());
        // Response is sent by the shard handler; if no handler stored it, ACK anyway
        await writeToSink(stream, new TextEncoder().encode('STORED'));
      } catch (error) {
        console.error(`[Protocol] Error storing shard:`, error);
      }
    });

    // Shard retrieval — looks up shard via the registered handler
    await this.node.handle(PROTOCOLS.SHARD_RETRIEVE, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const shardId = new TextDecoder().decode(data);

        // Try to retrieve from shard handler
        if (this.shardRetrieveHandler) {
          const shardData = await this.shardRetrieveHandler(shardId);
          if (shardData) {
            await writeToSink(stream, shardData);
            return;
          }
        }

        await writeToSink(stream, new TextEncoder().encode('SHARD_NOT_FOUND'));
      } catch (error) {
        console.error(`[Protocol] Error retrieving shard:`, error);
      }
    });

    // Call signaling
    await this.node.handle(PROTOCOLS.CALL_SIGNAL, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const signal = JSON.parse(new TextDecoder().decode(data));
        this.emit('call:incoming', signal, connection.remotePeer.toString());
        await writeToSink(stream, new TextEncoder().encode('SIGNAL_RECEIVED'));
      } catch (error) {
        console.error(`[Protocol] Error handling call signal:`, error);
      }
    });

    // Account bundle storage/retrieval
    await this.node.handle(PROTOCOLS.ACCOUNT_BUNDLE, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const request = JSON.parse(new TextDecoder().decode(data));

        if (request.action === 'store' && this.bundleStoreHandler) {
          await this.bundleStoreHandler(request.peerId, request.data);
          await writeToSink(stream, new TextEncoder().encode('STORED'));
        } else if (request.action === 'retrieve' && this.bundleRetrieveHandler) {
          const bundle = await this.bundleRetrieveHandler(request.peerId);
          if (bundle) {
            await writeToSink(stream, new TextEncoder().encode(bundle));
          } else {
            await writeToSink(stream, new TextEncoder().encode('NOT_FOUND'));
          }
        } else {
          await writeToSink(stream, new TextEncoder().encode('UNSUPPORTED'));
        }
      } catch (error) {
        console.error(`[Protocol] Error handling account bundle:`, error);
      }
    });

    // History sync — respond to recovery requests from contacts
    await this.node.handle(PROTOCOLS.HISTORY_SYNC, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const request = JSON.parse(new TextDecoder().decode(data));
        const libp2pId = connection.remotePeer.toString();
        const requesterId = this.libp2pToDecentra.get(libp2pId) || request.peerId;

        if (this.historySyncHandler) {
          const history = await this.historySyncHandler(requesterId, request.since || 0);
          if (history) {
            await writeToSink(stream, history);
          } else {
            await writeToSink(stream, new TextEncoder().encode('NO_HISTORY'));
          }
        } else {
          await writeToSink(stream, new TextEncoder().encode('UNSUPPORTED'));
        }
      } catch (error) {
        console.error(`[Protocol] Error handling history sync:`, error);
      }
    });

    console.log(`[Protocol] Registered handlers for: ${Object.values(PROTOCOLS).join(', ')}`);
  }
}

// ─── Profile Serialization ───────────────────────────────────────────────────

function serializeProfile(profile: PeerProfile): Record<string, unknown> {
  return {
    ...profile,
    publicKey: Buffer.from(profile.publicKey).toString('base64'),
    encryptionPublicKey: Buffer.from(profile.encryptionPublicKey).toString('base64'),
    signature: Buffer.from(profile.signature).toString('base64'),
  };
}

function deserializeProfile(raw: any): PeerProfile {
  return {
    ...raw,
    publicKey: new Uint8Array(Buffer.from(raw.publicKey, 'base64')),
    encryptionPublicKey: new Uint8Array(Buffer.from(raw.encryptionPublicKey, 'base64')),
    signature: new Uint8Array(Buffer.from(raw.signature, 'base64')),
  };
}

// ─── Stream Helpers (libp2p async iterable API) ──────────────────────────────

async function readFromSource(source: AsyncIterable<any>): Promise<Uint8Array> {
  const chunks: Uint8Array[] = [];
  for await (const chunk of source) {
    chunks.push(chunk.subarray());
  }
  return concatenateUint8Arrays(chunks);
}

async function writeToSink(stream: any, data: Uint8Array): Promise<void> {
  await stream.sink((async function* () {
    yield data;
  })());
}

function concatenateUint8Arrays(arrays: Uint8Array[]): Uint8Array {
  const totalLength = arrays.reduce((sum, arr) => sum + arr.length, 0);
  const result = new Uint8Array(totalLength);
  let offset = 0;
  for (const arr of arrays) {
    result.set(arr, offset);
    offset += arr.length;
  }
  return result;
}
