/**
 * Network Node — Core libp2p node setup and management
 *
 * Each running instance creates one of these nodes. It handles:
 * - Peer discovery (mDNS for local, DHT for global, bootstrap for initial)
 * - Encrypted connections between peers (Noise protocol)
 * - Stream multiplexing (Yamux)
 * - NAT traversal via circuit relay
 * - Custom protocol handlers
 * - Automatic profile exchange on connect (so peers get each other's encryption keys)
 *
 * Two ID systems are bridged here:
 * - libp2p PeerId: generated by libp2p from its own keys (e.g., 12D3KooW...)
 * - DecentraNet PeerId: base58 hash of our Ed25519 public key (e.g., 2q69Pfh...)
 * Users interact with DecentraNet PeerIds; libp2p PeerIds are internal plumbing.
 */

import { createLibp2p, type Libp2p } from 'libp2p';
import { FaultTolerance } from '@libp2p/interface';
import { tcp } from '@libp2p/tcp';
import { webSockets } from '@libp2p/websockets';
import { noise } from '@chainsafe/libp2p-noise';
import { yamux } from '@chainsafe/libp2p-yamux';
import { mdns } from '@libp2p/mdns';
import { kadDHT } from '@libp2p/kad-dht';
import { bootstrap } from '@libp2p/bootstrap';
import { identify } from '@libp2p/identify';
import { dcutr } from '@libp2p/dcutr';
import { circuitRelayTransport, circuitRelayServer } from '@libp2p/circuit-relay-v2';

import { multiaddr } from '@multiformats/multiaddr';
import { CID } from 'multiformats/cid';
import { sha256 } from 'multiformats/hashes/sha2';
import * as raw from 'multiformats/codecs/raw';
import { generateKeyPair, privateKeyFromProtobuf, privateKeyToProtobuf } from '@libp2p/crypto/keys';
import * as fs from 'fs';
import * as path from 'path';
import type { NodeConfig, Identity, PeerProfile, NetworkEvent, NetworkEventType } from '../types/index.js';
import { generateIdentity, loadIdentity, saveIdentity, publicKeyToPeerId, createPeerProfile, verifyPeerProfile } from '../crypto/identity.js';

/** Cached CID for the peer directory — all peers derive the same key */
let _directoryCID: CID | null = null;
async function getDirectoryCID(): Promise<CID> {
  if (_directoryCID) return _directoryCID;
  const bytes = new TextEncoder().encode('decentranet-peer-directory-v1');
  const hash = await sha256.digest(bytes);
  _directoryCID = CID.createV1(raw.code, hash);
  return _directoryCID;
}

/** Default bootstrap peers for the DecentraNet network */
const DEFAULT_BOOTSTRAP_PEERS: string[] = [
  '/ip4/188.166.151.203/tcp/6001/p2p/12D3KooWGoSh2awF3bJD7Y6a5Pwz4EPhwSFctPSjLyGEpuyt7Nx1',
  '/ip4/188.166.151.203/tcp/6002/ws/p2p/12D3KooWGoSh2awF3bJD7Y6a5Pwz4EPhwSFctPSjLyGEpuyt7Nx1',
];

/** Check if an IPv4 address is private, loopback, or otherwise non-routable */
function isPrivateOrUnroutableIP(ip: string): boolean {
  if (ip === '0.0.0.0' || ip === '127.0.0.1') return true;
  if (ip.startsWith('192.168.')) return true;
  if (ip.startsWith('10.')) return true;
  if (ip.startsWith('172.')) {
    const second = parseInt(ip.split('.')[1], 10);
    if (second >= 16 && second <= 31) return true;
  }
  if (ip.startsWith('169.254.')) return true; // link-local
  return false;
}

/** Filter multiaddrs to only include addresses routable by remote peers */
function getRoutableAddresses(addrs: string[]): string[] {
  return addrs.filter(addr => {
    // Extract the first IP — for circuit addresses this is the relay's IP
    const match = addr.match(/\/ip4\/([^/]+)\//);
    if (!match) return false;
    return !isPrivateOrUnroutableIP(match[1]);
  });
}

const PROTOCOL_PREFIX = '/decentranet';
export const PROTOCOLS = {
  MESSAGE: `${PROTOCOL_PREFIX}/message/1.0.0`,
  SHARD_STORE: `${PROTOCOL_PREFIX}/shard-store/1.0.0`,
  SHARD_RETRIEVE: `${PROTOCOL_PREFIX}/shard-retrieve/1.0.0`,
  CALL_SIGNAL: `${PROTOCOL_PREFIX}/call-signal/1.0.0`,
  PEER_EXCHANGE: `${PROTOCOL_PREFIX}/peer-exchange/1.0.0`,
  ACCOUNT_BUNDLE: `${PROTOCOL_PREFIX}/account-bundle/1.0.0`,
  HISTORY_SYNC: `${PROTOCOL_PREFIX}/history-sync/1.0.0`,
  PROFILE_UPDATE: `${PROTOCOL_PREFIX}/profile-update/1.0.0`,
  PEER_SEARCH: `${PROTOCOL_PREFIX}/peer-search/1.0.0`,
  FRIEND_REQUEST: `${PROTOCOL_PREFIX}/friend-request/1.0.0`,
  POST_BROADCAST: `${PROTOCOL_PREFIX}/post-broadcast/1.0.0`,
  POST_INTERACTION: `${PROTOCOL_PREFIX}/post-interaction/1.0.0`,
  VOUCH_BROADCAST: `${PROTOCOL_PREFIX}/vouch-broadcast/1.0.0`,
  DEAD_DROP_BROADCAST: `${PROTOCOL_PREFIX}/dead-drop-broadcast/1.0.0`,
  DEAD_DROP_RELAY: `${PROTOCOL_PREFIX}/dead-drop-relay/1.0.0`,
  POLL_BROADCAST: `${PROTOCOL_PREFIX}/poll-broadcast/1.0.0`,
  POLL_VOTE: `${PROTOCOL_PREFIX}/poll-vote/1.0.0`,
  HUB_SYNC: `${PROTOCOL_PREFIX}/hub-sync/1.0.0`,
  HUB_DISCOVERY: `${PROTOCOL_PREFIX}/hub-discovery/1.0.0`,
  DELETE_NOTIFY: `${PROTOCOL_PREFIX}/delete-notify/1.0.0`,
  ONION_RELAY: `${PROTOCOL_PREFIX}/onion-relay/1.0.0`,
  AUDIO_STREAM: `${PROTOCOL_PREFIX}/audio-stream/1.0.0`,
  FEED_SYNC: `${PROTOCOL_PREFIX}/feed-sync/1.0.0`,
} as const;

type EventHandler = (event: NetworkEvent) => void;

export class DecentraNode {
  private node: Libp2p | null = null;
  private config: NodeConfig;
  private identity: Identity;
  private eventHandlers: Map<NetworkEventType, EventHandler[]> = new Map();

  // Peer tracking: bridge between libp2p PeerIds and DecentraNet PeerIds
  private knownPeers: Map<string, PeerProfile> = new Map();        // decentraId -> profile
  private libp2pToDecentra: Map<string, string> = new Map();       // libp2pId -> decentraId
  private decentraToLibp2p: Map<string, string> = new Map();       // decentraId -> libp2pId
  private exchangeInProgress: Set<string> = new Set();              // libp2pIds currently exchanging
  private shardRetrieveHandler?: (shardId: string) => Promise<Uint8Array | null>;
  private bundleStoreHandler?: (peerId: string, data: string) => Promise<void>;
  private bundleRetrieveHandler?: (peerId: string) => Promise<string | null>;
  private historySyncHandler?: (requesterId: string, since: number) => Promise<Uint8Array | null>;
  private tofuHandler?: (peerId: string, publicKey: Uint8Array) => Promise<boolean>;
  private profileUpdateHandler?: (peerId: string, data: string) => Promise<void>;
  private peerSearchHandler?: (query: string, requesterId?: string) => Promise<string>;
  private friendRequestHandler?: (data: string) => Promise<string>;
  private postBroadcastHandler?: (data: string) => Promise<void>;
  private postInteractionHandler?: (data: string) => Promise<string>;
  private vouchBroadcastHandler?: (data: string) => Promise<void>;
  private deadDropBroadcastHandler?: (data: string) => Promise<void>;
  private deadDropRelayHandler?: (data: string) => Promise<void>;
  private pollBroadcastHandler?: (data: string) => Promise<void>;
  private pollVoteHandler?: (data: string) => Promise<void>;
  private hubSyncHandler?: (data: string) => Promise<string | void>;
  private hubDiscoveryHandler?: (data: string) => Promise<string | void>;
  private onionRelayHandler?: (data: string) => Promise<void>;
  private deleteNotifyHandler?: (data: string) => Promise<void>;
  private audioStreamHandler?: (peerId: string, chunk: Uint8Array) => void;
  private feedSyncHandler?: (data: string) => Promise<string>;
  private activeAudioStreams: Map<string, { pushable: any; stream: any }> = new Map();
  private passphrase: string;

  // Rate limiting: 100 messages per 60-second window per peer
  private rateLimiter: Map<string, { count: number; windowStart: number }> = new Map();
  private rateLimitCleanupTimer?: ReturnType<typeof setInterval>;

  // Peer reconnection state
  private peerLastLibp2pId: Map<string, string> = new Map();  // decentraId -> last known libp2pId
  private reconnectTimers: Map<string, NodeJS.Timeout> = new Map();
  private reconnectAttempts: Map<string, number> = new Map();
  private static MAX_RECONNECT_ATTEMPTS = 5;
  private static RECONNECT_DELAYS = [3000, 8000, 20000, 45000, 90000];

  // DHT directory publishing
  private directoryPublishTimer?: ReturnType<typeof setInterval>;
  private directoryPublishing = false;

  constructor(config: NodeConfig, passphrase: string) {
    this.passphrase = passphrase;
    this.config = config;

    try {
      this.identity = loadIdentity(config.identityPath, passphrase);
      console.log(`[Identity] Loaded existing identity`);
    } catch {
      console.log(`[Identity] Generating new identity...`);
      this.identity = generateIdentity(config.displayName);
      saveIdentity(this.identity, config.identityPath, passphrase);
    }

    console.log(`[Identity] Peer ID: ${this.getPeerId()}`);
    if (this.identity.displayName) {
      console.log(`[Identity] Display name: ${this.identity.displayName}`);
    }
  }

  async start(): Promise<void> {
    const wsPort = this.config.wsPort || this.config.port + 1;
    const isPublic = this.config.isPublic || false;

    console.log(`[Node] Starting on TCP:${this.config.port} WS:${wsPort}${isPublic ? ' (PUBLIC mode)' : ''}${this.config.disableMdns ? ' (mDNS disabled)' : ''}...`);

    // Merge default + user-supplied bootstrap peers
    const allBootstrapPeers = [
      ...DEFAULT_BOOTSTRAP_PEERS,
      ...this.config.bootstrapPeers,
    ].filter((addr, i, arr) => arr.indexOf(addr) === i); // dedupe

    // If an announce IP is set (e.g., public VPS IP), advertise those addresses
    const announce: string[] = [];
    if (this.config.announceIp) {
      announce.push(`/ip4/${this.config.announceIp}/tcp/${this.config.port}`);
      announce.push(`/ip4/${this.config.announceIp}/tcp/${wsPort}/ws`);
    }

    // Build circuit relay listen addresses — explicitly target public bootstrap relays
    // so we get a reservation on a publicly-routable relay, not just a LAN peer
    const circuitListenAddrs: string[] = [];
    if (!isPublic) {
      // Pick the first TCP (non-WS) bootstrap peer for an explicit relay reservation
      const tcpBootstrap = allBootstrapPeers.find(a => !a.includes('/ws/'));
      if (tcpBootstrap) {
        circuitListenAddrs.push(`${tcpBootstrap}/p2p-circuit`);
      } else {
        circuitListenAddrs.push('/p2p-circuit'); // fallback: discover any relay
      }
    }

    // Persist libp2p key so the PeerId stays stable across restarts
    // (critical for bootstrap addresses to remain valid)
    const libp2pKeyPath = path.join(this.config.dataDir, 'libp2p-key');
    let libp2pPrivateKey;
    try {
      const raw = fs.readFileSync(libp2pKeyPath);
      libp2pPrivateKey = privateKeyFromProtobuf(raw);
      console.log(`[Node] Loaded persisted libp2p key`);
    } catch {
      libp2pPrivateKey = await generateKeyPair('Ed25519');
      if (!fs.existsSync(this.config.dataDir)) fs.mkdirSync(this.config.dataDir, { recursive: true });
      fs.writeFileSync(libp2pKeyPath, privateKeyToProtobuf(libp2pPrivateKey));
      console.log(`[Node] Generated and saved new libp2p key`);
    }

    const libp2pConfig: any = {
      privateKey: libp2pPrivateKey,
      addresses: {
        listen: [
          `/ip4/0.0.0.0/tcp/${this.config.port}`,
          `/ip4/0.0.0.0/tcp/${wsPort}/ws`,
          ...circuitListenAddrs,
        ],
        ...(announce.length > 0 ? { announce } : {}),
      },
      transports: [
        tcp(),
        webSockets(),
        circuitRelayTransport({ reservationConcurrency: 1 }),
      ],
      connectionEncrypters: [noise()],
      streamMuxers: [yamux()],
      services: {
        identify: identify(),
        dht: kadDHT({
          protocol: '/decentranet/kad/1.0.0',
          clientMode: !isPublic,
        }),
        dcutr: dcutr(),
      },
      peerDiscovery: this.config.disableMdns ? [] : [mdns()],
      transportManager: {
        faultTolerance: FaultTolerance.NO_FATAL,
      },
    };

    if (allBootstrapPeers.length > 0) {
      libp2pConfig.peerDiscovery.push(
        bootstrap({ list: allBootstrapPeers })
      );
    }

    // Public nodes always run the relay server; private nodes only if configured
    // Defaults are way too restrictive (15 reservations, 128KB data, 2min duration)
    // — bump to production-grade limits for a messaging network
    if (isPublic || this.config.enableRelay) {
      libp2pConfig.services.relay = circuitRelayServer({
        reservations: {
          maxReservations: 256,
          reservationTtl: 2 * 60 * 60 * 1000,       // 2 hours
          applyDefaultLimit: true,
          defaultDurationLimit: 2 * 60 * 60 * 1000,   // 2 hours per relayed connection
          defaultDataLimit: BigInt(100 * 1024 * 1024), // 100 MB per direction
        },
      });
    }

    this.node = await createLibp2p(libp2pConfig);
    this.setupEventListeners();
    await this.registerProtocolHandlers();
    await this.node.start();

    // Clean stale rate limit entries every 5 minutes
    this.rateLimitCleanupTimer = setInterval(() => this.cleanRateLimiter(), 5 * 60 * 1000);

    const addresses = this.node.getMultiaddrs();
    console.log(`[Node] Listening on:`);
    addresses.forEach((addr) => console.log(`  ${addr.toString()}`));

    if (isPublic) {
      console.log(`[Node] PUBLIC mode — this node is a DHT server and circuit relay`);
    } else {
      console.log(`[Node] DHT client mode (behind NAT). Use --public on public-facing nodes.`);
    }

    console.log(`[Node] Node started successfully`);
  }

  async stop(): Promise<void> {
    this.stopDirectoryPublishing();
    if (this.rateLimitCleanupTimer) {
      clearInterval(this.rateLimitCleanupTimer);
      this.rateLimitCleanupTimer = undefined;
    }
    // Cancel all pending reconnection timers
    for (const [decentraId, timer] of this.reconnectTimers) {
      clearTimeout(timer);
    }
    this.reconnectTimers.clear();
    this.reconnectAttempts.clear();
    if (this.node) {
      console.log(`[Node] Shutting down...`);
      await this.node.stop();
      console.log(`[Node] Stopped`);
    }
  }

  // ─── Identity & Addressing ──────────────────────────────────────────────

  getPeerId(): string {
    return publicKeyToPeerId(this.identity.publicKey);
  }

  getLibp2pPeerId(): string {
    if (!this.node) throw new Error('Node not started');
    return this.node.peerId.toString();
  }

  getLibp2p(): Libp2p {
    if (!this.node) throw new Error('Node not started');
    return this.node;
  }

  getIdentity(): Identity {
    return this.identity;
  }

  getAddresses(): string[] {
    if (!this.node) return [];
    return this.node.getMultiaddrs().map((addr) => addr.toString());
  }

  getProfile(): PeerProfile {
    return createPeerProfile(this.identity, this.getAddresses());
  }

  /** Profile for PEER_EXCHANGE — omits addresses to avoid leaking IPs to all peers */
  getExchangeProfile(): PeerProfile {
    return createPeerProfile(this.identity, []);
  }

  setDisplayName(name: string): void {
    this.identity.displayName = name;
    saveIdentity(this.identity, this.config.identityPath, this.passphrase);
  }

  // ─── Peer Management ────────────────────────────────────────────────────

  /** Get all connected libp2p peer IDs */
  getConnectedLibp2pPeers(): string[] {
    if (!this.node) return [];
    return this.node.getPeers().map((p) => p.toString());
  }

  /** Get all connected peers with their DecentraNet profiles (only exchanged ones) */
  getConnectedPeers(): { libp2pId: string; decentraId?: string; profile?: PeerProfile }[] {
    const libp2pPeers = this.getConnectedLibp2pPeers();
    return libp2pPeers.map((libp2pId) => {
      const decentraId = this.libp2pToDecentra.get(libp2pId);
      return {
        libp2pId,
        decentraId,
        profile: decentraId ? this.knownPeers.get(decentraId) : undefined,
      };
    });
  }

  /** Get a peer profile by DecentraNet PeerId */
  getKnownPeer(decentraId: string): PeerProfile | undefined {
    return this.knownPeers.get(decentraId);
  }

  /** Get all known peer profiles */
  getAllKnownPeers(): PeerProfile[] {
    return Array.from(this.knownPeers.values());
  }

  /** Manually register a peer profile (e.g., from storage on startup) */
  registerKnownPeer(profile: PeerProfile, libp2pId?: string): void {
    this.knownPeers.set(profile.peerId, profile);
    if (libp2pId) {
      this.libp2pToDecentra.set(libp2pId, profile.peerId);
      this.decentraToLibp2p.set(profile.peerId, libp2pId);
    }
  }

  /** Resolve a DecentraNet PeerId to a libp2p PeerId */
  resolveDecentraId(decentraId: string): string | undefined {
    return this.decentraToLibp2p.get(decentraId);
  }

  /** Resolve a libp2p PeerId to a DecentraNet PeerId */
  resolveLibp2pId(libp2pId: string): string | undefined {
    return this.libp2pToDecentra.get(libp2pId);
  }

  /** Check if a peer has exceeded the rate limit (100 msg / 60s) */
  private isRateLimited(peerId: string): boolean {
    const now = Date.now();
    const entry = this.rateLimiter.get(peerId);

    if (!entry || now - entry.windowStart > 60_000) {
      this.rateLimiter.set(peerId, { count: 1, windowStart: now });
      return false;
    }

    entry.count++;
    if (entry.count > 100) {
      console.warn(`[RateLimit] Peer ${peerId} exceeded 100 msg/60s — dropping message`);
      return true;
    }
    return false;
  }

  /** Remove stale rate limit entries older than 2 minutes */
  private cleanRateLimiter(): void {
    const cutoff = Date.now() - 120_000;
    for (const [peerId, entry] of this.rateLimiter) {
      if (entry.windowStart < cutoff) {
        this.rateLimiter.delete(peerId);
      }
    }
  }

  // ─── Peer Reconnection ──────────────────────────────────────────────────

  /** Check if we have an active libp2p connection to a peer */
  private hasActiveConnection(libp2pId: string): boolean {
    if (!this.node) return false;
    return this.node.getConnections().some(c => c.remotePeer.toString() === libp2pId);
  }

  /** Find the last-known libp2p PeerId for a decentra peer */
  private findLibp2pIdForPeer(decentraId: string): string | undefined {
    // Check current mapping first
    const current = this.decentraToLibp2p.get(decentraId);
    if (current) return current;
    // Fall back to last-known mapping
    return this.peerLastLibp2pId.get(decentraId);
  }

  /** Schedule reconnection to a known peer with exponential backoff */
  private scheduleReconnect(decentraId: string): void {
    // Don't schedule if already pending
    if (this.reconnectTimers.has(decentraId)) return;

    const attempt = this.reconnectAttempts.get(decentraId) || 0;
    if (attempt >= DecentraNode.MAX_RECONNECT_ATTEMPTS) {
      console.log(`[Reconnect] Giving up on ${decentraId.slice(0, 12)} after ${attempt} attempts`);
      this.reconnectAttempts.delete(decentraId);
      return;
    }

    const delay = DecentraNode.RECONNECT_DELAYS[attempt] || 30000;
    console.log(`[Reconnect] Scheduling attempt ${attempt + 1}/${DecentraNode.MAX_RECONNECT_ATTEMPTS} for ${decentraId.slice(0, 12)} in ${delay / 1000}s`);

    const timer = setTimeout(async () => {
      this.reconnectTimers.delete(decentraId);
      this.reconnectAttempts.set(decentraId, attempt + 1);

      // Check if already reconnected (e.g. peer dialed us)
      const currentLibp2pId = this.decentraToLibp2p.get(decentraId);
      if (currentLibp2pId && this.hasActiveConnection(currentLibp2pId)) {
        console.log(`[Reconnect] ${decentraId.slice(0, 12)} already reconnected`);
        this.reconnectAttempts.delete(decentraId);
        return;
      }

      const success = await this.reconnectPeer(decentraId);
      if (success) {
        console.log(`[Reconnect] Successfully reconnected to ${decentraId.slice(0, 12)}`);
        this.reconnectAttempts.delete(decentraId);
      } else {
        // Schedule next attempt
        this.scheduleReconnect(decentraId);
      }
    }, delay);

    this.reconnectTimers.set(decentraId, timer);
  }

  /** Cancel pending reconnection for a peer */
  private cancelReconnect(decentraId: string): void {
    const timer = this.reconnectTimers.get(decentraId);
    if (timer) {
      clearTimeout(timer);
      this.reconnectTimers.delete(decentraId);
      this.reconnectAttempts.delete(decentraId);
      console.log(`[Reconnect] Cancelled reconnection for ${decentraId.slice(0, 12)} (peer reconnected)`);
    }
  }

  /** Attempt to reconnect to a known peer via profile addresses or relay fallback */
  private async reconnectPeer(decentraId: string): Promise<boolean> {
    const profile = this.knownPeers.get(decentraId);
    if (!profile || !this.node) return false;

    console.log(`[Reconnect] Attempting reconnect to ${profile.displayName || decentraId.slice(0, 12)}...`);

    // Try profile addresses first (relay addresses sorted first — most likely to work across NAT)
    if (profile.addresses && profile.addresses.length > 0) {
      const addrs = [...profile.addresses].sort((a, b) => {
        const aRelay = a.includes('/p2p-circuit/') ? 0 : 1;
        const bRelay = b.includes('/p2p-circuit/') ? 0 : 1;
        return aRelay - bRelay;
      });

      for (const addr of addrs) {
        try {
          await this.node.dial(multiaddr(addr), { signal: AbortSignal.timeout(8000) });
          return true;
        } catch {}
      }
    }

    // Relay fallback: construct circuit address through bootstrap peers
    const libp2pId = this.findLibp2pIdForPeer(decentraId);
    if (libp2pId) {
      for (const relayAddr of DEFAULT_BOOTSTRAP_PEERS) {
        if (relayAddr.includes('/ws/')) continue; // skip WS duplicates
        const circuitAddr = `${relayAddr}/p2p-circuit/p2p/${libp2pId}`;
        try {
          console.log(`[Reconnect] Trying relay circuit: ${circuitAddr.slice(0, 60)}...`);
          await this.node.dial(multiaddr(circuitAddr), { signal: AbortSignal.timeout(10000) });
          return true;
        } catch (err: any) {
          console.log(`[Reconnect] Relay dial failed: ${err?.message?.slice(0, 80) || 'unknown'}`);
        }
      }
    } else {
      console.log(`[Reconnect] No last-known libp2p ID for ${decentraId.slice(0, 12)} — cannot construct relay address`);
    }

    return false;
  }

  /** Register a handler to serve shard retrieve requests */
  setShardRetrieveHandler(handler: (shardId: string) => Promise<Uint8Array | null>): void {
    this.shardRetrieveHandler = handler;
  }

  /** Register handlers for account bundle store/retrieve */
  setBundleHandlers(
    store: (peerId: string, data: string) => Promise<void>,
    retrieve: (peerId: string) => Promise<string | null>,
  ): void {
    this.bundleStoreHandler = store;
    this.bundleRetrieveHandler = retrieve;
  }

  /** Register a handler for history sync requests */
  setHistorySyncHandler(handler: (requesterId: string, since: number) => Promise<Uint8Array | null>): void {
    this.historySyncHandler = handler;
  }

  /**
   * Register a TOFU handler. Called during profile exchange.
   * Returns true if the key is trusted (first-seen or matches pin), false if changed.
   */
  setTofuHandler(handler: (peerId: string, publicKey: Uint8Array) => Promise<boolean>): void {
    this.tofuHandler = handler;
  }

  /** Register handler for profile updates (Phase 2) */
  setProfileUpdateHandler(handler: (peerId: string, data: string) => Promise<void>): void {
    this.profileUpdateHandler = handler;
  }

  /** Register handler for peer search queries (Phase 3) */
  setPeerSearchHandler(handler: (query: string, requesterId?: string) => Promise<string>): void {
    this.peerSearchHandler = handler;
  }

  /** Register handler for friend requests (Phase 3) */
  setFriendRequestHandler(handler: (data: string) => Promise<string>): void {
    this.friendRequestHandler = handler;
  }

  /** Register handler for post broadcasts (Phase 4) */
  setPostBroadcastHandler(handler: (data: string) => Promise<void>): void {
    this.postBroadcastHandler = handler;
  }

  /** Register handler for post interactions (Phase 4) */
  setPostInteractionHandler(handler: (data: string) => Promise<string>): void {
    this.postInteractionHandler = handler;
  }

  /** Register handler for vouch broadcasts (Trust Web) */
  setVouchBroadcastHandler(handler: (data: string) => Promise<void>): void {
    this.vouchBroadcastHandler = handler;
  }

  /** Register handler for dead drop broadcasts */
  setDeadDropBroadcastHandler(handler: (data: string) => Promise<void>): void {
    this.deadDropBroadcastHandler = handler;
  }

  /** Register handler for dead drop relay (onion routing) */
  setDeadDropRelayHandler(handler: (data: string) => Promise<void>): void {
    this.deadDropRelayHandler = handler;
  }

  /** Register handler for poll broadcasts */
  setPollBroadcastHandler(handler: (data: string) => Promise<void>): void {
    this.pollBroadcastHandler = handler;
  }

  /** Register handler for poll votes */
  setPollVoteHandler(handler: (data: string) => Promise<void>): void {
    this.pollVoteHandler = handler;
  }

  /** Register handler for hub sync messages */
  setHubSyncHandler(handler: (data: string) => Promise<string | void>): void {
    this.hubSyncHandler = handler;
  }

  /** Register handler for hub discovery messages */
  setHubDiscoveryHandler(handler: (data: string) => Promise<string | void>): void {
    this.hubDiscoveryHandler = handler;
  }

  /** Register handler for onion relay cells */
  setOnionRelayHandler(handler: (data: string) => Promise<void>): void {
    this.onionRelayHandler = handler;
  }

  /** Register handler for delete notifications */
  setDeleteNotifyHandler(handler: (data: string) => Promise<void>): void {
    this.deleteNotifyHandler = handler;
  }

  /** Register handler for feed sync requests */
  setFeedSyncHandler(handler: (data: string) => Promise<string>): void {
    this.feedSyncHandler = handler;
  }

  /** Register handler for incoming audio stream chunks */
  setAudioStreamHandler(handler: (peerId: string, chunk: Uint8Array) => void): void {
    this.audioStreamHandler = handler;
  }

  /** Open a persistent bidirectional audio stream to a peer */
  async openAudioStream(decentraId: string): Promise<boolean> {
    if (!this.node) return false;
    if (this.activeAudioStreams.has(decentraId)) return true; // Already open

    const libp2pId = this.decentraToLibp2p.get(decentraId);
    if (!libp2pId) return false;

    const connections = this.node.getConnections();
    const conn = connections.find(c => c.remotePeer.toString() === libp2pId);
    if (!conn) return false;

    try {
      const stream = await this.node.dialProtocol(
        conn.remotePeer,
        PROTOCOLS.AUDIO_STREAM,
        { runOnLimitedConnection: true }
      );

      const { pushable } = await import('it-pushable');
      const outbound = pushable<Uint8Array>();
      this.activeAudioStreams.set(decentraId, { pushable: outbound, stream });

      // Feed outbound audio to stream sink (runs concurrently)
      const sinkPromise = stream.sink(outbound).catch(() => {});

      // Read inbound audio from stream source
      (async () => {
        try {
          for await (const chunk of stream.source) {
            const data = chunk.subarray();
            if (this.audioStreamHandler) {
              this.audioStreamHandler(decentraId, data);
            }
          }
        } catch {} finally {
          outbound.end();
          this.activeAudioStreams.delete(decentraId);
          await sinkPromise;
          console.log(`[Audio] Stream to ${decentraId.slice(0, 12)} ended`);
        }
      })();

      console.log(`[Audio] Opened audio stream to ${decentraId.slice(0, 12)}`);
      return true;
    } catch (error: any) {
      console.error(`[Audio] Failed to open stream to ${decentraId.slice(0, 12)}:`, error.message);
      return false;
    }
  }

  /** Push an audio chunk to the active stream for a peer */
  pushAudioChunk(decentraId: string, chunk: Uint8Array): boolean {
    const entry = this.activeAudioStreams.get(decentraId);
    if (!entry) return false;
    entry.pushable.push(chunk);
    return true;
  }

  /** Close the audio stream to a peer */
  closeAudioStream(decentraId: string): void {
    const entry = this.activeAudioStreams.get(decentraId);
    if (entry) {
      entry.pushable.end();
      this.activeAudioStreams.delete(decentraId);
      console.log(`[Audio] Closed stream to ${decentraId.slice(0, 12)}`);
    }
  }

  /** Public wrapper for reconnectPeer — used by startup reconnection */
  async reconnectPeerPublic(decentraId: string): Promise<boolean> {
    return this.reconnectPeer(decentraId);
  }

  /** Broadcast data to all connected peers on a given protocol */
  async broadcastToAll(protocol: string, data: Uint8Array): Promise<void> {
    const peers = this.getConnectedPeers();
    for (const peer of peers) {
      if (peer.decentraId) {
        this.sendToPeer(peer.decentraId, protocol, data).catch(() => {});
      }
    }
  }

  /** Find a peer by display name (partial match, prefers connected peers) */
  findPeerByName(name: string): PeerProfile | undefined {
    const lower = name.toLowerCase();
    const connectedDecentraIds = new Set(
      this.getConnectedLibp2pPeers()
        .map((id) => this.libp2pToDecentra.get(id))
        .filter(Boolean)
    );

    let fallback: PeerProfile | undefined;
    for (const profile of this.knownPeers.values()) {
      if (profile.displayName?.toLowerCase().includes(lower)) {
        if (connectedDecentraIds.has(profile.peerId)) return profile;
        if (!fallback) fallback = profile;
      }
    }
    return fallback;
  }

  // ─── Invite Codes ──────────────────────────────────────────────────────

  /**
   * Generate a base64url invite code containing our multiaddrs and identity.
   * Other peers can use this to connect to us directly.
   * Filters out private/non-routable IPs so the code works across the internet.
   */
  getInviteCode(): string {
    const allAddrs = this.getAddresses()
      .filter((a) => !a.includes('/::1/'));

    // Filter to only public + relay addresses (remove 0.0.0.0, 192.168.x, 10.x, etc.)
    const addrs = getRoutableAddresses(allAddrs);

    if (addrs.length === 0) {
      console.warn('[Invite] WARNING: No public or relay addresses available');
      console.warn('[Invite] This invite code will only work on the local network');
      console.warn('[Invite] To fix: ensure connection to a relay node, or use --announce-ip <your-public-ip>');
    }

    const payload = {
      v: 1,
      a: addrs,
      d: this.getPeerId(),
      l: this.node ? this.node.peerId.toString() : undefined, // libp2p PeerId for relay fallback
      n: this.identity.displayName || undefined,
    };

    const json = JSON.stringify(payload);
    const b64 = Buffer.from(json).toString('base64')
      .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    return b64;
  }

  /**
   * Connect to a peer using their invite code.
   * Decodes the code, dials their multiaddrs, and returns their DecentraNet ID on success.
   * Tries relay circuit addresses first, then direct, then relay fallback.
   */
  async connectWithInvite(code: string): Promise<{ peerId: string; name?: string }> {
    if (!this.node) throw new Error('Node not started');

    // Decode base64url
    const padded = code.replace(/-/g, '+').replace(/_/g, '/');
    const json = Buffer.from(padded, 'base64').toString('utf-8');

    let payload: { v: number; a: string[]; d: string; l?: string; n?: string };
    try {
      payload = JSON.parse(json);
    } catch {
      throw new Error('Invalid invite code — could not parse');
    }

    if (!payload.v || !payload.a || !payload.d) {
      throw new Error('Invalid invite code — missing fields');
    }

    console.log(`[Invite] Connecting to ${payload.n || payload.d}...`);

    // Sort: relay addresses first (most likely to work across NAT), then direct
    const sortedAddrs = [...payload.a].sort((a, b) => {
      const aRelay = a.includes('/p2p-circuit/') ? 0 : 1;
      const bRelay = b.includes('/p2p-circuit/') ? 0 : 1;
      return aRelay - bRelay;
    });

    console.log(`[Invite] Trying ${sortedAddrs.length} address(es)...`);

    // Try each multiaddr with a 10-second timeout
    let connected = false;
    let connectedLibp2pId: string | undefined;
    for (const addr of sortedAddrs) {
      try {
        console.log(`[Invite] Dialing ${addr}...`);
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 10_000);
        try {
          const conn = await this.node.dial(multiaddr(addr), { signal: controller.signal });
          connected = true;
          connectedLibp2pId = conn.remotePeer.toString();
          console.log(`[Invite] Connected via ${addr}`);
          break;
        } finally {
          clearTimeout(timeout);
        }
      } catch (error: any) {
        const msg = error.message || error.code || 'unknown';
        console.log(`[Invite] Failed: ${addr} (${msg.includes('abort') ? 'timeout' : msg})`);
      }
    }

    // Relay fallback: if direct dials failed and we have the libp2p PeerId,
    // try connecting through known relay nodes via circuit relay
    if (!connected && payload.l) {
      console.log(`[Invite] Direct dials failed — trying relay fallback...`);

      for (const relayAddr of DEFAULT_BOOTSTRAP_PEERS) {
        // Skip WS duplicates (only need one transport per relay)
        if (relayAddr.includes('/ws/')) continue;

        const circuitAddr = `${relayAddr}/p2p-circuit/p2p/${payload.l}`;
        try {
          console.log(`[Invite] Trying relay: ${circuitAddr}`);
          const controller = new AbortController();
          const timeout = setTimeout(() => controller.abort(), 15_000);
          try {
            const conn = await this.node.dial(multiaddr(circuitAddr), { signal: controller.signal });
            connected = true;
            connectedLibp2pId = conn.remotePeer.toString();
            console.log(`[Invite] Connected via circuit relay!`);
            break;
          } finally {
            clearTimeout(timeout);
          }
        } catch (error: any) {
          const msg = error.message || error.code || 'unknown';
          console.log(`[Invite] Relay failed: ${msg.includes('abort') ? 'timeout' : msg}`);
        }
      }
    }

    if (!connected) {
      const hint = payload.l
        ? 'Neither direct nor relay connections worked. Ensure both peers can reach the relay node.'
        : 'Invite code has no relay info. Ask the peer to regenerate their invite code after connecting to the network.';
      throw new Error(`Could not connect to peer — ${hint}`);
    }

    // Immediately register the ID mapping so sendToPeer() works right away
    // Always update — a reconnection may have a new libp2p PeerId
    const libp2pId = connectedLibp2pId || payload.l;
    if (libp2pId && payload.d) {
      this.libp2pToDecentra.set(libp2pId, payload.d);
      this.decentraToLibp2p.set(payload.d, libp2pId);
      console.log(`[Invite] Registered ID mapping: ${payload.d.slice(0, 12)} ↔ ${libp2pId.slice(0, 12)}`);

      // Wait for profile exchange to complete — this populates the real crypto keys
      // needed for encryption. Without this, messaging/invites fail with DECODE_ERROR.
      try {
        await Promise.race([
          this.initiateProfileExchange(libp2pId),
          new Promise<void>((_, reject) => setTimeout(() => reject(new Error('timeout')), 10_000)),
        ]);
        console.log(`[Invite] Profile exchange completed for ${payload.n || payload.d.slice(0, 12)}`);
      } catch {
        console.warn(`[Invite] Profile exchange timed out — registering minimal profile`);
        // Fallback: register minimal profile so peer at least appears in contacts
        // (crypto operations won't work until a successful exchange later)
        if (!this.knownPeers.has(payload.d)) {
          this.knownPeers.set(payload.d, {
            peerId: payload.d,
            publicKey: new Uint8Array(0),
            encryptionPublicKey: new Uint8Array(0),
            displayName: payload.n || payload.d.slice(0, 12),
            addresses: payload.a || [],
            lastSeen: Date.now(),
            version: 0,
            signature: new Uint8Array(0),
          });
        }
      }
    }

    return { peerId: payload.d, name: payload.n };
  }

  // ─── DHT Peer Directory ─────────────────────────────────────────────────

  /** Publish ourselves as a provider of the directory CID so other peers can find us */
  async publishToDirectory(): Promise<void> {
    if (!this.node) return;
    try {
      const cid = await getDirectoryCID();
      await this.node.contentRouting.provide(cid);
      console.log(`[Directory] Published to DHT peer directory`);
    } catch (error: any) {
      // Graceful — DHT may not be ready yet, or no peers to publish to
      const msg = error?.message || String(error);
      if (!msg.includes('not started') && !msg.includes('No peers')) {
        console.warn(`[Directory] Publish failed: ${msg}`);
      }
    }
  }

  /** Start periodic directory publishing (5s initial delay, then every 10 min) */
  startDirectoryPublishing(): void {
    if (this.directoryPublishing) return;
    this.directoryPublishing = true;
    console.log(`[Directory] Starting DHT directory publishing`);

    // Initial publish after 5s delay (let connections stabilize)
    setTimeout(() => {
      if (!this.directoryPublishing) return;
      this.publishToDirectory();
    }, 5_000);

    // Re-publish every 10 minutes to keep the DHT record alive
    this.directoryPublishTimer = setInterval(() => {
      this.publishToDirectory();
    }, 10 * 60 * 1000);
  }

  /** Stop directory publishing */
  stopDirectoryPublishing(): void {
    if (!this.directoryPublishing) return;
    this.directoryPublishing = false;
    if (this.directoryPublishTimer) {
      clearInterval(this.directoryPublishTimer);
      this.directoryPublishTimer = undefined;
    }
    console.log(`[Directory] Stopped DHT directory publishing`);
  }

  /** Whether directory publishing is active */
  isDirectoryPublishing(): boolean {
    return this.directoryPublishing;
  }

  /**
   * Discover peers via the DHT directory.
   * Finds providers of the directory CID, connects to unknown ones (triggers profile exchange),
   * waits briefly for profiles, then filters by search term.
   */
  async discoverPeers(searchTerm?: string, maxResults = 20, timeoutMs = 15_000): Promise<{ peerId: string; displayName: string; isOnline: boolean; source: string }[]> {
    if (!this.node) return [];

    const cid = await getDirectoryCID();
    const myLibp2pId = this.node.peerId.toString();
    const newPeerIds: string[] = [];

    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), timeoutMs);

      try {
        for await (const provider of this.node.contentRouting.findProviders(cid, { signal: controller.signal })) {
          const providerLibp2pId = provider.id.toString();
          if (providerLibp2pId === myLibp2pId) continue;

          // Check if we already know this peer
          const existingDecentraId = this.libp2pToDecentra.get(providerLibp2pId);
          if (existingDecentraId) continue;

          // Try to connect (this triggers profile exchange via peer:connect event)
          const existingConns = this.node.getConnections().filter(
            (c) => c.remotePeer.toString() === providerLibp2pId
          );
          if (existingConns.length === 0) {
            try {
              await this.node.dial(provider.id);
              newPeerIds.push(providerLibp2pId);
            } catch {
              // Peer unreachable — skip
            }
          }
        }
      } finally {
        clearTimeout(timeout);
      }
    } catch (error: any) {
      // AbortError is expected (timeout), other errors are worth logging
      if (error?.name !== 'AbortError' && !error?.message?.includes('abort')) {
        console.warn(`[Directory] Discovery error: ${error?.message || error}`);
      }
    }

    // Wait for profile exchanges to complete for newly connected peers
    if (newPeerIds.length > 0) {
      await new Promise(resolve => setTimeout(resolve, 2_000));
    }

    // Collect all known peers with source tag
    const term = (searchTerm || '').toLowerCase();
    const myId = this.getPeerId();
    const connectedDecentraIds = new Set(
      this.getConnectedLibp2pPeers()
        .map((id) => this.libp2pToDecentra.get(id))
        .filter(Boolean)
    );

    const results: { peerId: string; displayName: string; isOnline: boolean; source: string }[] = [];
    for (const profile of this.knownPeers.values()) {
      if (profile.peerId === myId) continue;
      if (term && !(profile.displayName || '').toLowerCase().includes(term) && !profile.peerId.toLowerCase().includes(term)) continue;
      results.push({
        peerId: profile.peerId,
        displayName: profile.displayName || profile.peerId.slice(0, 12),
        isOnline: connectedDecentraIds.has(profile.peerId),
        source: 'dht',
      });
      if (results.length >= maxResults) break;
    }

    console.log(`[Directory] Discovered ${newPeerIds.length} new peer(s), ${results.length} total result(s)`);
    return results;
  }

  // ─── Events ─────────────────────────────────────────────────────────────

  on(event: NetworkEventType, handler: EventHandler): void {
    const handlers = this.eventHandlers.get(event) || [];
    handlers.push(handler);
    this.eventHandlers.set(event, handlers);
  }

  private emit(type: NetworkEventType, data?: unknown, peerId?: string): void {
    const event: NetworkEvent = { type, data, peerId, timestamp: Date.now() };
    const handlers = this.eventHandlers.get(type) || [];
    handlers.forEach((h) => h(event));
  }

  // ─── Communication ──────────────────────────────────────────────────────

  /**
   * Send data to a peer identified by their DecentraNet PeerId.
   * Resolves the DecentraNet ID to a libp2p connection and sends.
   */
  async sendToPeer(decentraId: string, protocol: string, data: Uint8Array): Promise<Uint8Array | null> {
    let libp2pId = this.decentraToLibp2p.get(decentraId);

    // If no mapping or no active connection, try to reconnect
    if (!libp2pId || !this.hasActiveConnection(libp2pId)) {
      if (this.knownPeers.has(decentraId)) {
        console.log(`[Node] No active connection to ${decentraId.slice(0, 12)} — attempting reconnect...`);
        const reconnected = await this.reconnectPeer(decentraId);
        if (reconnected) {
          libp2pId = this.decentraToLibp2p.get(decentraId);
        }
      }
    }

    if (!libp2pId) {
      console.log(`[Node] Unknown peer ${decentraId} — no libp2p mapping`);
      return null;
    }
    return this.sendToLibp2pPeer(libp2pId, protocol, data);
  }

  /**
   * Send data to a peer identified by their libp2p PeerId.
   */
  async sendToLibp2pPeer(libp2pId: string, protocol: string, data: Uint8Array): Promise<Uint8Array | null> {
    if (!this.node) throw new Error('Node not started');

    try {
      const connections = this.node.getConnections();
      const conn = connections.find((c) => c.remotePeer.toString() === libp2pId);

      if (!conn) {
        console.log(`[Node] No active connection to ${libp2pId}`);
        return null;
      }

      const stream = await this.node.dialProtocol(conn.remotePeer, protocol, { runOnLimitedConnection: true });

      // Write request
      await stream.sink((async function* () {
        yield data;
      })());

      // Read response
      const chunks: Uint8Array[] = [];
      for await (const chunk of stream.source) {
        chunks.push(chunk.subarray());
      }

      return chunks.length > 0 ? concatenateUint8Arrays(chunks) : null;
    } catch (error: any) {
      const msg = error?.message || error?.code || String(error);
      // Suppress noisy connection errors (dead peers, EOF, reset)
      if (msg.includes('EOF') || msg.includes('ECONNRESET') || msg.includes('stream ended')) {
        console.log(`[Node] Connection to ${libp2pId} lost (${error?.code || 'EOF'})`);
      } else {
        console.error(`[Node] Failed to send to ${libp2pId}:`, msg);
      }
      return null;
    }
  }

  // ─── Profile Exchange ───────────────────────────────────────────────────

  /**
   * Initiate a profile exchange with a connected libp2p peer.
   * Sends our profile and receives theirs. Called automatically on connect.
   */
  private async initiateProfileExchange(libp2pId: string): Promise<void> {
    if (this.exchangeInProgress.has(libp2pId)) return;
    this.exchangeInProgress.add(libp2pId);

    try {
      const ourProfile = this.getExchangeProfile();
      const profileData = serializeProfile(ourProfile);
      const data = new TextEncoder().encode(JSON.stringify(profileData));

      const response = await this.sendToLibp2pPeer(libp2pId, PROTOCOLS.PEER_EXCHANGE, data);

      if (response) {
        const theirProfileData = JSON.parse(new TextDecoder().decode(response));
        const theirProfile = deserializeProfile(theirProfileData);

        if (verifyPeerProfile(theirProfile)) {
          // TOFU check — reject peer if key changed (don't silently accept)
          if (this.tofuHandler) {
            const trusted = await this.tofuHandler(theirProfile.peerId, theirProfile.publicKey);
            if (!trusted) {
              console.warn(`[TOFU] Key change detected for ${theirProfile.peerId}! Rejecting peer.`);
              this.emit('peer:key_changed', {
                peerId: theirProfile.peerId,
                displayName: theirProfile.displayName,
              }, theirProfile.peerId);
              return; // Do NOT register — key mismatch
            }
          }
          this.registerKnownPeer(theirProfile, libp2pId);
          const name = theirProfile.displayName || theirProfile.peerId.slice(0, 12);
          console.log(`[Exchange] Received profile from ${name} (${theirProfile.peerId})`);
          this.emit('peer:connected', theirProfile, theirProfile.peerId);
        } else {
          console.warn(`[Exchange] Profile from ${libp2pId} failed signature verification`);
        }
      }
    } catch (error) {
      console.error(`[Exchange] Failed with ${libp2pId}:`, error);
    } finally {
      this.exchangeInProgress.delete(libp2pId);
    }
  }

  // ─── Private Setup ──────────────────────────────────────────────────────

  private setupEventListeners(): void {
    if (!this.node) return;

    this.node.addEventListener('peer:connect', (event) => {
      const libp2pId = event.detail.toString();
      console.log(`[Node] Peer connected: ${libp2pId}`);

      // Cancel any pending reconnection for this peer
      const decentraId = this.libp2pToDecentra.get(libp2pId);
      if (decentraId) {
        this.cancelReconnect(decentraId);
      }

      // Auto-exchange profiles after a short delay (let the connection stabilize)
      // Retry once at 2s if the first attempt fails
      setTimeout(async () => {
        await this.initiateProfileExchange(libp2pId);
        if (!this.libp2pToDecentra.has(libp2pId)) {
          setTimeout(() => this.initiateProfileExchange(libp2pId), 1500);
        }
      }, 300);
    });

    this.node.addEventListener('peer:disconnect', (event) => {
      const libp2pId = event.detail.toString();
      const decentraId = this.libp2pToDecentra.get(libp2pId);
      console.log(`[Node] Peer disconnected: ${libp2pId}${decentraId ? ` (${decentraId})` : ''}`);

      // Clean up stale ID mapping so reconnection can register a fresh one
      if (decentraId) {
        this.peerLastLibp2pId.set(decentraId, libp2pId);
        this.libp2pToDecentra.delete(libp2pId);
        this.decentraToLibp2p.delete(decentraId);

        // Schedule reconnection for known peers (contacts we've exchanged profiles with)
        if (this.knownPeers.has(decentraId)) {
          this.scheduleReconnect(decentraId);
        }
      }

      this.emit('peer:disconnected', undefined, decentraId || libp2pId);
    });

    // Log when relay circuit addresses are acquired
    this.node.addEventListener('self:peer:update', () => {
      if (!this.node) return;
      const relayAddrs = this.node.getMultiaddrs()
        .filter((a) => a.toString().includes('/p2p-circuit/'));
      if (relayAddrs.length > 0) {
        console.log(`[Relay] Circuit relay addresses available:`);
        relayAddrs.forEach((a) => console.log(`  ${a.toString()}`));
      }
    });

    this.node.addEventListener('peer:discovery', async (event) => {
      const peerInfo = event.detail;
      const libp2pId = peerInfo.id.toString();
      console.log(`[Node] Discovered peer: ${libp2pId}`);

      // Auto-dial discovered peers if we're not already connected
      if (!this.node) return;
      const existingConns = this.node.getConnections().filter(
        (c) => c.remotePeer.toString() === libp2pId
      );
      if (existingConns.length === 0) {
        try {
          console.log(`[Node] Dialing discovered peer ${libp2pId}...`);
          await this.node.dial(peerInfo.id);
        } catch (error) {
          // Dial failures are expected (e.g., peer went offline)
          console.log(`[Node] Could not dial ${libp2pId}`);
        }
      }
    });
  }

  private async registerProtocolHandlers(): Promise<void> {
    if (!this.node) return;

    // All protocols must work over relay-routed (limited) connections
    const limitedOk = { runOnLimitedConnection: true };

    // Peer exchange: receive their profile, send ours back
    await this.node.handle(PROTOCOLS.PEER_EXCHANGE, async ({ stream, connection }) => {
      const libp2pId = connection.remotePeer.toString();
      try {
        const data = await readFromSource(stream.source);
        const theirProfileData = JSON.parse(new TextDecoder().decode(data));
        const theirProfile = deserializeProfile(theirProfileData);

        if (verifyPeerProfile(theirProfile)) {
          // TOFU check — reject peer if key changed (don't silently accept)
          let tofuRejected = false;
          if (this.tofuHandler) {
            const trusted = await this.tofuHandler(theirProfile.peerId, theirProfile.publicKey);
            if (!trusted) {
              console.warn(`[TOFU] Key change detected for ${theirProfile.peerId}! Rejecting peer.`);
              this.emit('peer:key_changed', {
                peerId: theirProfile.peerId,
                displayName: theirProfile.displayName,
              }, theirProfile.peerId);
              tofuRejected = true;
            }
          }
          if (!tofuRejected) {
            this.registerKnownPeer(theirProfile, libp2pId);
            const name = theirProfile.displayName || theirProfile.peerId.slice(0, 12);
            console.log(`[Exchange] Received profile from ${name} (${theirProfile.peerId})`);
            this.emit('peer:connected', theirProfile, theirProfile.peerId);
          }
        } else {
          console.warn(`[Exchange] Profile from ${libp2pId} failed verification`);
        }

        // Send our profile back (without addresses to avoid IP leakage)
        const ourProfile = this.getExchangeProfile();
        const responseData = new TextEncoder().encode(JSON.stringify(serializeProfile(ourProfile)));
        await writeToSink(stream, responseData);
      } catch (error) {
        console.error(`[Exchange] Error handling profile exchange:`, error);
      }
    }, limitedOk);

    // Message delivery
    await this.node.handle(PROTOCOLS.MESSAGE, async ({ stream, connection }) => {
      const libp2pId = connection.remotePeer.toString();
      if (this.isRateLimited(libp2pId)) { try { await stream.close(); } catch {} return; }
      const decentraId = this.libp2pToDecentra.get(libp2pId);
      try {
        const data = await readFromSource(stream.source);
        this.emit('message:received', data, decentraId || libp2pId);
        await writeToSink(stream, new TextEncoder().encode('ACK'));
      } catch (error) {
        console.error(`[Protocol] Error handling message:`, error);
      }
    }, limitedOk);

    // Shard storage
    await this.node.handle(PROTOCOLS.SHARD_STORE, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        this.emit('shard:stored', data, connection.remotePeer.toString());
        // Response is sent by the shard handler; if no handler stored it, ACK anyway
        await writeToSink(stream, new TextEncoder().encode('STORED'));
      } catch (error) {
        console.error(`[Protocol] Error storing shard:`, error);
      }
    }, limitedOk);

    // Shard retrieval — looks up shard via the registered handler
    await this.node.handle(PROTOCOLS.SHARD_RETRIEVE, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const shardId = new TextDecoder().decode(data);

        // Try to retrieve from shard handler
        if (this.shardRetrieveHandler) {
          const shardData = await this.shardRetrieveHandler(shardId);
          if (shardData) {
            await writeToSink(stream, shardData);
            return;
          }
        }

        await writeToSink(stream, new TextEncoder().encode('SHARD_NOT_FOUND'));
      } catch (error) {
        console.error(`[Protocol] Error retrieving shard:`, error);
      }
    }, limitedOk);

    // Call signaling
    await this.node.handle(PROTOCOLS.CALL_SIGNAL, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const signal = JSON.parse(new TextDecoder().decode(data));
        this.emit('call:incoming', signal, connection.remotePeer.toString());
        await writeToSink(stream, new TextEncoder().encode('SIGNAL_RECEIVED'));
      } catch (error) {
        console.error(`[Protocol] Error handling call signal:`, error);
      }
    }, { ...limitedOk, maxInboundStreams: 16 });

    // Account bundle storage/retrieval
    await this.node.handle(PROTOCOLS.ACCOUNT_BUNDLE, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const request = JSON.parse(new TextDecoder().decode(data));

        if (request.action === 'store' && this.bundleStoreHandler) {
          await this.bundleStoreHandler(request.peerId, request.data);
          await writeToSink(stream, new TextEncoder().encode('STORED'));
        } else if (request.action === 'retrieve' && this.bundleRetrieveHandler) {
          const bundle = await this.bundleRetrieveHandler(request.peerId);
          if (bundle) {
            await writeToSink(stream, new TextEncoder().encode(bundle));
          } else {
            await writeToSink(stream, new TextEncoder().encode('NOT_FOUND'));
          }
        } else {
          await writeToSink(stream, new TextEncoder().encode('UNSUPPORTED'));
        }
      } catch (error) {
        console.error(`[Protocol] Error handling account bundle:`, error);
      }
    }, limitedOk);

    // History sync — respond to recovery requests from contacts
    await this.node.handle(PROTOCOLS.HISTORY_SYNC, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const request = JSON.parse(new TextDecoder().decode(data));
        const libp2pId = connection.remotePeer.toString();
        const requesterId = this.libp2pToDecentra.get(libp2pId);

        if (!requesterId) {
          console.warn(`[HistorySync] Rejected: no verified identity for ${libp2pId} (PEER_EXCHANGE not complete)`);
          await writeToSink(stream, new TextEncoder().encode('UNAUTHORIZED'));
          return;
        }

        if (this.historySyncHandler) {
          const history = await this.historySyncHandler(requesterId, request.since || 0);
          if (history) {
            await writeToSink(stream, history);
          } else {
            await writeToSink(stream, new TextEncoder().encode('NO_HISTORY'));
          }
        } else {
          await writeToSink(stream, new TextEncoder().encode('UNSUPPORTED'));
        }
      } catch (error) {
        console.error(`[Protocol] Error handling history sync:`, error);
      }
    }, limitedOk);

    // Profile update (Phase 2)
    await this.node.handle(PROTOCOLS.PROFILE_UPDATE, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        const libp2pId = connection.remotePeer.toString();
        const decentraId = this.libp2pToDecentra.get(libp2pId);
        if (this.profileUpdateHandler && decentraId) {
          await this.profileUpdateHandler(decentraId, text);
        }
        await writeToSink(stream, new TextEncoder().encode('OK'));
      } catch (error) {
        console.error(`[Protocol] Error handling profile update:`, error);
      }
    }, limitedOk);

    // Peer search (Phase 3)
    await this.node.handle(PROTOCOLS.PEER_SEARCH, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const query = new TextDecoder().decode(data);
        const requesterId = this.libp2pToDecentra.get(connection.remotePeer.toString());
        if (this.peerSearchHandler) {
          const results = await this.peerSearchHandler(query, requesterId);
          await writeToSink(stream, new TextEncoder().encode(results));
        } else {
          await writeToSink(stream, new TextEncoder().encode('[]'));
        }
      } catch (error) {
        console.error(`[Protocol] Error handling peer search:`, error);
      }
    }, limitedOk);

    // Friend request (Phase 3)
    await this.node.handle(PROTOCOLS.FRIEND_REQUEST, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.friendRequestHandler) {
          const response = await this.friendRequestHandler(text);
          await writeToSink(stream, new TextEncoder().encode(response));
        } else {
          await writeToSink(stream, new TextEncoder().encode('UNSUPPORTED'));
        }
      } catch (error) {
        console.error(`[Protocol] Error handling friend request:`, error);
      }
    }, limitedOk);

    // Post broadcast (Phase 4)
    await this.node.handle(PROTOCOLS.POST_BROADCAST, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.postBroadcastHandler) {
          await this.postBroadcastHandler(text);
        }
        await writeToSink(stream, new TextEncoder().encode('OK'));
      } catch (error) {
        console.error(`[Protocol] Error handling post broadcast:`, error);
      }
    }, limitedOk);

    // Post interaction (Phase 4)
    await this.node.handle(PROTOCOLS.POST_INTERACTION, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.postInteractionHandler) {
          const response = await this.postInteractionHandler(text);
          await writeToSink(stream, new TextEncoder().encode(response));
        } else {
          await writeToSink(stream, new TextEncoder().encode('UNSUPPORTED'));
        }
      } catch (error) {
        console.error(`[Protocol] Error handling post interaction:`, error);
      }
    }, limitedOk);

    // Vouch broadcast (Trust Web)
    await this.node.handle(PROTOCOLS.VOUCH_BROADCAST, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.vouchBroadcastHandler) {
          await this.vouchBroadcastHandler(text);
        }
        await writeToSink(stream, new TextEncoder().encode('OK'));
      } catch (error) {
        console.error(`[Protocol] Error handling vouch broadcast:`, error);
      }
    }, limitedOk);

    // Dead drop broadcast
    await this.node.handle(PROTOCOLS.DEAD_DROP_BROADCAST, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.deadDropBroadcastHandler) {
          await this.deadDropBroadcastHandler(text);
        }
        await writeToSink(stream, new TextEncoder().encode('OK'));
      } catch (error) {
        console.error(`[Protocol] Error handling dead drop broadcast:`, error);
      }
    }, limitedOk);

    // Dead drop relay (onion routing)
    await this.node.handle(PROTOCOLS.DEAD_DROP_RELAY, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.deadDropRelayHandler) {
          await this.deadDropRelayHandler(text);
        }
        await writeToSink(stream, new TextEncoder().encode('OK'));
      } catch (error) {
        console.error(`[Protocol] Error handling dead drop relay:`, error);
      }
    }, limitedOk);

    // Poll broadcast (polls + results, differentiated by type field)
    await this.node.handle(PROTOCOLS.POLL_BROADCAST, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.pollBroadcastHandler) {
          await this.pollBroadcastHandler(text);
        }
        await writeToSink(stream, new TextEncoder().encode('OK'));
      } catch (error) {
        console.error(`[Protocol] Error handling poll broadcast:`, error);
      }
    }, limitedOk);

    // Poll vote (direct peer-to-peer: voter -> creator)
    await this.node.handle(PROTOCOLS.POLL_VOTE, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.pollVoteHandler) {
          await this.pollVoteHandler(text);
        }
        await writeToSink(stream, new TextEncoder().encode('VOTE_RECEIVED'));
      } catch (error) {
        console.error(`[Protocol] Error handling poll vote:`, error);
      }
    }, limitedOk);

    // Hub sync (invites, messages, state sync, updates)
    await this.node.handle(PROTOCOLS.HUB_SYNC, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.hubSyncHandler) {
          const response = await this.hubSyncHandler(text);
          await writeToSink(stream, new TextEncoder().encode(response || 'OK'));
        } else {
          await writeToSink(stream, new TextEncoder().encode('OK'));
        }
      } catch (error) {
        console.error(`[Protocol] Error handling hub sync:`, error);
      }
    }, limitedOk);

    // Hub discovery (public hub listings, search)
    await this.node.handle(PROTOCOLS.HUB_DISCOVERY, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.hubDiscoveryHandler) {
          const response = await this.hubDiscoveryHandler(text);
          await writeToSink(stream, new TextEncoder().encode(response || 'OK'));
        } else {
          await writeToSink(stream, new TextEncoder().encode('OK'));
        }
      } catch (error) {
        console.error(`[Protocol] Error handling hub discovery:`, error);
      }
    }, limitedOk);

    // Onion relay (general-purpose onion routing)
    await this.node.handle(PROTOCOLS.ONION_RELAY, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.onionRelayHandler) {
          await this.onionRelayHandler(text);
        }
        await writeToSink(stream, new TextEncoder().encode('OK'));
      } catch (error) {
        console.error(`[Protocol] Error handling onion relay:`, error);
      }
    }, limitedOk);

    // Delete notifications
    await this.node.handle(PROTOCOLS.DELETE_NOTIFY, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.deleteNotifyHandler) {
          await this.deleteNotifyHandler(text);
        }
        await writeToSink(stream, new TextEncoder().encode('OK'));
      } catch (error) {
        console.error(`[Protocol] Error handling delete notification:`, error);
      }
    }, limitedOk);

    // Feed sync — exchange broadcast posts between peers
    await this.node.handle(PROTOCOLS.FEED_SYNC, async ({ stream, connection }) => {
      if (this.isRateLimited(connection.remotePeer.toString())) { try { await stream.close(); } catch {} return; }
      try {
        const data = await readFromSource(stream.source);
        const text = new TextDecoder().decode(data);
        if (this.feedSyncHandler) {
          const response = await this.feedSyncHandler(text);
          await writeToSink(stream, new TextEncoder().encode(response));
        } else {
          await writeToSink(stream, new TextEncoder().encode('UNSUPPORTED'));
        }
      } catch (error) {
        console.error(`[Protocol] Error handling feed sync:`, error);
      }
    }, { ...limitedOk, maxInboundStreams: 4 });

    // Audio streaming — persistent bidirectional stream for voice-over-libp2p
    await this.node.handle(PROTOCOLS.AUDIO_STREAM, async ({ stream, connection }) => {
      const libp2pId = connection.remotePeer.toString();
      const decentraId = this.libp2pToDecentra.get(libp2pId);
      if (!decentraId) {
        try { await stream.close(); } catch {}
        return;
      }

      console.log(`[Audio] Incoming audio stream from ${decentraId.slice(0, 12)}`);

      const { pushable } = await import('it-pushable');
      const outbound = pushable<Uint8Array>();
      this.activeAudioStreams.set(decentraId, { pushable: outbound, stream });

      // Feed outbound audio to the stream sink (runs concurrently)
      const sinkPromise = stream.sink(outbound).catch(() => {});

      // Read inbound audio chunks from the stream source
      try {
        for await (const chunk of stream.source) {
          const data = chunk.subarray();
          if (this.audioStreamHandler) {
            this.audioStreamHandler(decentraId, data);
          }
        }
      } catch {
        // Stream closed or errored
      } finally {
        outbound.end();
        this.activeAudioStreams.delete(decentraId);
        await sinkPromise;
        console.log(`[Audio] Audio stream from ${decentraId.slice(0, 12)} ended`);
      }
    }, { ...limitedOk, maxInboundStreams: 2 });

    console.log(`[Protocol] Registered handlers for: ${Object.values(PROTOCOLS).join(', ')}`);
  }
}

// ─── Profile Serialization ───────────────────────────────────────────────────

function serializeProfile(profile: PeerProfile): Record<string, unknown> {
  return {
    ...profile,
    publicKey: Buffer.from(profile.publicKey).toString('base64'),
    encryptionPublicKey: Buffer.from(profile.encryptionPublicKey).toString('base64'),
    signature: Buffer.from(profile.signature).toString('base64'),
  };
}

function deserializeProfile(raw: any): PeerProfile {
  return {
    ...raw,
    publicKey: new Uint8Array(Buffer.from(raw.publicKey, 'base64')),
    encryptionPublicKey: new Uint8Array(Buffer.from(raw.encryptionPublicKey, 'base64')),
    signature: new Uint8Array(Buffer.from(raw.signature, 'base64')),
  };
}

// ─── Stream Helpers (libp2p async iterable API) ──────────────────────────────

const MAX_STREAM_BYTES = 200 * 1024 * 1024; // 200MB — supports Pro tier shards (500MB file / 4 shards + encoding overhead)

async function readFromSource(source: AsyncIterable<any>): Promise<Uint8Array> {
  const chunks: Uint8Array[] = [];
  let totalBytes = 0;
  for await (const chunk of source) {
    const bytes = chunk.subarray();
    totalBytes += bytes.length;
    if (totalBytes > MAX_STREAM_BYTES) {
      throw new Error(`Stream exceeded ${MAX_STREAM_BYTES} byte limit`);
    }
    chunks.push(bytes);
  }
  return concatenateUint8Arrays(chunks);
}

async function writeToSink(stream: any, data: Uint8Array): Promise<void> {
  await stream.sink((async function* () {
    yield data;
  })());
}

function concatenateUint8Arrays(arrays: Uint8Array[]): Uint8Array {
  const totalLength = arrays.reduce((sum, arr) => sum + arr.length, 0);
  const result = new Uint8Array(totalLength);
  let offset = 0;
  for (const arr of arrays) {
    result.set(arr, offset);
    offset += arr.length;
  }
  return result;
}
